"""
streamlit_app.py
----------------
LUAD Precision Oncology Platform — Interactive Dashboard

Displays pre-computed analysis results from the 7-module pipeline.
Run with:  streamlit run streamlit_app.py
"""

import streamlit as st
import pandas as pd
from pathlib import Path

# ── Page config (must be first Streamlit call) ─────────────────────────────
st.set_page_config(
    page_title="LUAD Precision Oncology Platform",
    page_icon="🫁",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Bottom-left site link ───────────────────────────────────────────────────
st.markdown("""
<style>
.bottom-link {
    position: fixed;
    bottom: 16px;
    left: 24px;
    z-index: 9999;
    background-color: #1565c0;
    border-radius: 8px;
    padding: 8px 16px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.30);
}
.bottom-link a {
    color: #ffffff !important;
    text-decoration: none !important;
    font-size: 0.88rem;
    font-weight: 600;
    letter-spacing: 0.2px;
}
.bottom-link a:hover {
    color: #bbdefb !important;
}
</style>
<div class="bottom-link">
    <a href="https://yujuan-zhang.github.io/" title="Yujuan Zhang, PhD">Yujuan Zhang, PhD</a>
</div>
""", unsafe_allow_html=True)

# ── Paths ──────────────────────────────────────────────────────────────────
# All output files live under data/output/, relative to this script
OUTPUT = Path(__file__).parent / "data" / "output"

# ── Per-module sample discovery ────────────────────────────────────────────
def discover_module_samples(module_out_dir: Path, file_suffix: str) -> list:
    """Return sorted list of patient IDs that have output for a given module."""
    if not module_out_dir.exists():
        return []
    return sorted([
        d.name for d in module_out_dir.iterdir()
        if d.is_dir() and (d / f"{d.name}{file_suffix}").exists()
    ])

def discover_clinical_samples() -> list:
    """Return patient IDs from the clinical TSV (broadest list)."""
    tsv = Path(__file__).parent / "data" / "clinical" / "tcga_luad_clinical.tsv"
    if not tsv.exists():
        return []
    try:
        df = pd.read_csv(tsv, sep="\t", usecols=["sample_id"])
        return sorted(df["sample_id"].dropna().tolist())
    except Exception:
        return []

# Global fallback (used when page doesn't have its own selector)
SAMPLES = discover_module_samples(OUTPUT / "02_variants", "_variants.tsv.gz") \
          or ["TCGA-86-A4D0", "TCGA-49-4507"]

@st.cache_data
def load_cohort_index() -> pd.DataFrame:
    """Load cross-module modality index generated by run_all.py."""
    path = Path(__file__).parent / "data" / "output" / "cohort_index.tsv"
    if path.exists():
        return pd.read_csv(path, sep="\t")
    # Fallback: build from filesystem if file not yet generated
    idx = pd.DataFrame({"sample_id": SAMPLES})
    idx["has_rnaseq"]     = idx["sample_id"].apply(lambda s: (OUTPUT / "03_expression" / s).exists())
    idx["has_wes"]        = idx["sample_id"].apply(lambda s: (OUTPUT / "02_variants" / s).exists())
    idx["has_pathology"]  = idx["sample_id"].apply(lambda s: (OUTPUT / "05_pathology" / s).exists())
    idx["has_proteomics"] = False
    idx["modality_count"] = idx[["has_rnaseq","has_wes","has_pathology","has_proteomics"]].sum(axis=1)
    return idx

def patients_for_page(page: str) -> list:
    """Return the appropriate patient list for each module page."""
    idx = load_cohort_index()
    if page in ("07 · Variant Impact",):
        return idx[idx.has_wes]["sample_id"].tolist()
    if page in ("09 · Multimodal Integration", "10 · Clinical Recommendation"):
        return idx[idx.has_wes & idx.has_rnaseq]["sample_id"].tolist()
    if page in ("05 · Pathology",):
        return idx[idx.has_pathology]["sample_id"].tolist()
    return idx["sample_id"].tolist()

# ── Helper: safe image display ─────────────────────────────────────────────
def show_image(path: Path, caption: str = "", width: int = None):
    """Display an image if the file exists, otherwise show a warning."""
    if path.exists():
        if width:
            st.image(str(path), caption=caption, width=width)
        else:
            st.image(str(path), caption=caption, use_container_width=True)
    else:
        st.info(f"Output not yet available: `{path.name}`\n\nRun the pipeline to generate this file.")


# ── Helper: safe table display ─────────────────────────────────────────────
def show_table(path: Path, sep: str = "\t", nrows: int = 200, caption: str = ""):
    """Display a TSV/CSV as a Streamlit dataframe, with row limit for large files."""
    if not path.exists():
        st.info(f"Output not yet available: `{path.name}`")
        return
    try:
        df = pd.read_csv(path, sep=sep, nrows=nrows)
        if caption:
            st.caption(caption)
        st.dataframe(df, use_container_width=True)
        if len(df) == nrows:
            st.caption(f"Showing first {nrows} rows. Full file: `{path}`")
    except Exception as e:
        st.error(f"Could not load `{path.name}`: {e}")


# ── Pipeline architecture figure ───────────────────────────────────────────
@st.cache_data
def make_pipeline_figure():
    """Generate the 8-module pipeline architecture diagram. Returns a PNG BytesIO."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        from matplotlib.patches import FancyBboxPatch
    except ImportError:
        return None

    fig, ax = plt.subplots(figsize=(12, 11))
    ax.set_xlim(0, 12)
    ax.set_ylim(0, 12)
    ax.axis("off")
    fig.patch.set_facecolor("#ffffff")

    def fbox(x, y, w, h, bg, bd, lw=1.5):
        ax.add_patch(FancyBboxPatch(
            (x, y), w, h, boxstyle="round,pad=0.12",
            facecolor=bg, edgecolor=bd, linewidth=lw, zorder=3,
        ))

    def txt(x, y, s, size=9, color="#1a1a2e", bold=False, ha="center", va="center"):
        ax.text(x, y, s, fontsize=size, color=color,
                fontweight="bold" if bold else "normal",
                ha=ha, va=va, zorder=4, multialignment="center")

    def arrow_dn(x, y_start, y_end):
        ax.annotate("", xy=(x, y_end), xytext=(x, y_start),
                    arrowprops=dict(arrowstyle="-|>", color="#607d8b",
                                   lw=1.8, mutation_scale=16), zorder=2)

    def arrow_rt(x_start, x_end, y):
        ax.annotate("", xy=(x_end, y), xytext=(x_start, y),
                    arrowprops=dict(arrowstyle="-|>", color="#9c27b0",
                                   lw=1.5, mutation_scale=14), zorder=2)

    # Title
    txt(6.0, 11.55, "Pipeline Architecture", size=13, bold=True, color="#1a1a2e")

    # INPUT — two data sources
    fbox(0.3, 10.05, 11.4, 0.95, "#f5f5f5", "#9e9e9e", lw=1.5)
    txt(6.0, 10.65, "INPUT", size=8.5, bold=True, color="#555")
    txt(6.0, 10.25,
        "MAF (somatic variants)  ·  RNA-seq TPM  ·  GDC clinical  ·  H&E WSI slides",
        size=7.5, color="#777")
    arrow_dn(6.0, 10.05, 9.32)

    # STAGE 1 — M01–M04 molecular + M08 imaging (parallel)
    fbox(0.2, 7.60, 11.6, 1.70, "#e3f2fd", "#1565c0", lw=2)
    txt(0.55, 9.13, "STAGE 1  —  Independent modules (run in parallel)",
        size=8.5, bold=True, color="#1565c0", ha="left")
    bw, bh1 = 2.0, 1.05

    # M01–M04
    for i, (num, name) in enumerate([
        ("01", "Patient\nContext"), ("02", "Variation\nAnnotation"),
        ("03", "Expression\nAnalysis"), ("04", "Single-Cell\nTME"),
    ]):
        xi = 0.4 + i * 2.3
        fbox(xi, 7.75, bw, bh1, "white", "#1565c0", lw=1.5)
        txt(xi + bw / 2, 7.75 + bh1 * 0.70, f"M{num}", size=10, bold=True, color="#1565c0")
        txt(xi + bw / 2, 7.75 + bh1 * 0.28, name, size=7.5, color="#333")

    # M08 — imaging module (purple, same stage)
    fbox(9.6, 7.75, bw, bh1, "#f3e5f5", "#6a1b9a", lw=1.8)
    txt(9.6 + bw / 2, 7.75 + bh1 * 0.70, "M08", size=10, bold=True, color="#6a1b9a")
    txt(9.6 + bw / 2, 7.75 + bh1 * 0.28, "Computational\nPathology", size=7.5, color="#333")

    arrow_dn(5.6, 7.60, 6.87)

    # STAGE 2
    fbox(1.3, 5.20, 8.4, 1.65, "#e8f5e9", "#2e7d32", lw=2)
    txt(1.65, 6.68, "STAGE 2  —  Depends on Stage 1 outputs",
        size=8.5, bold=True, color="#2e7d32", ha="left")
    bh2 = 1.08
    for (num, name), xi in zip(
        [("05", "Pathway\nEnrichment"), ("07", "Drug\nMapping")], [2.5, 5.9]
    ):
        fbox(xi, 5.37, bw, bh2, "white", "#2e7d32", lw=1.5)
        txt(xi + bw / 2, 5.37 + bh2 * 0.70, f"M{num}", size=10, bold=True, color="#2e7d32")
        txt(xi + bw / 2, 5.37 + bh2 * 0.28, name, size=7.5, color="#333")

    # M08 feeds into Stage 2 via arrow
    arrow_rt(10.6, 9.7, 6.28)
    fbox(9.6, 5.37, bw, bh2, "#f3e5f5", "#6a1b9a", lw=1.5)
    txt(9.6 + bw / 2, 5.37 + bh2 * 0.70, "M08", size=10, bold=True, color="#6a1b9a")
    txt(9.6 + bw / 2, 5.37 + bh2 * 0.28, "Pathology\nReport", size=7.5, color="#333")

    arrow_dn(5.6, 5.20, 4.52)

    # STAGE 3
    fbox(2.8, 3.05, 5.4, 1.45, "#fff3e0", "#e65100", lw=2)
    txt(3.10, 4.35, "STAGE 3  —  GPU recommended (optional)",
        size=8.5, bold=True, color="#e65100", ha="left")
    fbox(4.4, 3.20, bw, 0.95, "white", "#e65100", lw=1.5)
    txt(4.4 + bw / 2, 3.20 + 0.95 * 0.70, "M06", size=10, bold=True, color="#e65100")
    txt(4.4 + bw / 2, 3.20 + 0.95 * 0.28, "ESM2\nEmbeddings", size=7.5, color="#333")
    arrow_dn(5.6, 3.05, 2.37)

    # DASHBOARD
    fbox(2.0, 1.40, 8.0, 0.95, "#1565c0", "#0d47a1", lw=2)
    txt(6.0, 1.93, "STREAMLIT DASHBOARD", size=10.5, bold=True, color="white")
    txt(6.0, 1.58, "Interactive multi-omics + pathology results explorer", size=7.5, color="#bbdefb")

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=150, bbox_inches="tight",
                facecolor="white", edgecolor="none")
    buf.seek(0)
    plt.close(fig)
    return buf


# ══════════════════════════════════════════════════════════════════════════════
# SIDEBAR
# ══════════════════════════════════════════════════════════════════════════════

with st.sidebar:
    st.markdown("## 🫁 LUAD Platform")
    st.markdown("**Precision Oncology · Multi-Omics**")
    st.divider()

    # Page selector
    page = st.radio(
        "Navigate",
        options=[
            "Home",
            "01 · Patients",
            "02 · Variants",
            "03 · Expression",
            "04 · Single-Cell TME",
            "05 · Pathology",
            "06 · Pathway",
            "07 · Variant Impact",
            "08 · Multi-modal Immune Activity Score",
            "09 · Multimodal Integration",
            "10 · Clinical Recommendation",
        ],
        label_visibility="collapsed",
    )

    st.divider()
    st.caption("Data: TCGA-LUAD · GSE131907")
    st.caption("Model: ESM2-650M · PCGR v2.2.5")


# ══════════════════════════════════════════════════════════════════════════════
# HOME PAGE
# ══════════════════════════════════════════════════════════════════════════════

if page == "Home":

    # ── Global CSS ──────────────────────────────────────────────────────────
    st.markdown("""
    <style>
    /* Hero banner */
    .hero-banner {
        background: linear-gradient(150deg, #0a1628 0%, #12263f 55%, #0f3460 100%);
        border-radius: 14px;
        padding: 52px 48px 44px 48px;
        margin-bottom: 28px;
        color: white;
        position: relative;
        overflow: hidden;
    }
    .hero-accent {
        position: absolute;
        top: 0; left: 0; right: 0;
        height: 4px;
        background: linear-gradient(90deg, #1976d2, #42a5f5, #64b5f6, #29b6f6);
        border-radius: 14px 14px 0 0;
    }
    .hero-eyebrow {
        font-size: 0.70rem;
        letter-spacing: 2.5px;
        color: #42a5f5;
        text-transform: uppercase;
        font-weight: 700;
        margin-bottom: 14px;
    }
    .hero-title {
        font-size: 2.75rem;
        font-weight: 800;
        margin: 0 0 14px 0;
        letter-spacing: -0.8px;
        line-height: 1.15;
    }
    .hero-subtitle {
        font-size: 0.98rem;
        color: #b0c4de;
        margin: 0 0 28px 0;
        font-weight: 400;
        line-height: 1.65;
        max-width: 680px;
    }
    /* Badge pills — outlined style */
    .badge-row { margin-top: 0; display: flex; flex-wrap: wrap; gap: 8px; }
    .badge {
        display: inline-block;
        padding: 4px 14px;
        border-radius: 20px;
        font-size: 0.74rem;
        font-weight: 600;
        letter-spacing: 0.4px;
        border: 1px solid;
    }
    .badge-blue   { border-color: #42a5f5; color: #90caf9; }
    .badge-green  { border-color: #66bb6a; color: #a5d6a7; }
    .badge-purple { border-color: #ba68c8; color: #ce93d8; }
    .badge-orange { border-color: #ffa726; color: #ffcc80; }
    .badge-teal   { border-color: #26a69a; color: #80cbc4; }
    /* Stat cards */
    .stat-grid {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 16px;
        margin-bottom: 32px;
    }
    .stat-card {
        background: #f8f9fa;
        border: 1px solid #e0e0e0;
        border-left: 5px solid #1565c0;
        border-radius: 10px;
        padding: 20px 18px;
        text-align: center;
    }
    .stat-number { font-size: 2rem; font-weight: 800; color: #1565c0; }
    .stat-label  { font-size: 0.82rem; color: #666; margin-top: 4px; }
    /* Module cards */
    .module-grid {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 14px;
        margin-bottom: 32px;
    }
    .module-card {
        border: 1px solid #e0e0e0;
        border-radius: 10px;
        padding: 16px 18px;
        background: white;
        transition: box-shadow 0.2s;
    }
    .module-card:hover { box-shadow: 0 4px 12px rgba(0,0,0,0.1); }
    .module-id {
        display: inline-block;
        background: #1565c0;
        color: white;
        border-radius: 6px;
        padding: 2px 8px;
        font-size: 0.75rem;
        font-weight: 700;
        margin-right: 8px;
    }
    .module-name { font-weight: 700; font-size: 0.97rem; color: #1a1a2e; }
    .module-desc { font-size: 0.82rem; color: #666; margin-top: 6px; }
    .module-tag  {
        display: inline-block;
        background: #e8f0fe;
        color: #1a73e8;
        border-radius: 4px;
        padding: 1px 7px;
        font-size: 0.7rem;
        margin: 4px 3px 0 0;
    }
    /* Pipeline flow */
    .flow-step {
        display: flex;
        align-items: flex-start;
        gap: 16px;
        margin-bottom: 18px;
    }
    .flow-num {
        min-width: 36px;
        height: 36px;
        background: #1565c0;
        color: white;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        font-weight: 800;
        font-size: 0.9rem;
        flex-shrink: 0;
    }
    .flow-text strong { font-size: 0.95rem; color: #1a1a2e; }
    .flow-text p { font-size: 0.83rem; color: #666; margin: 2px 0 0 0; }
    /* Section headings */
    .section-heading {
        font-size: 1.2rem;
        font-weight: 700;
        color: #1a1a2e;
        border-bottom: 2px solid #1565c0;
        padding-bottom: 6px;
        margin: 28px 0 18px 0;
    }
    /* Overview cards */
    .overview-section {
        display: grid;
        grid-template-columns: 1fr 1fr 1fr;
        gap: 20px;
        margin-bottom: 32px;
    }
    .overview-card {
        border-radius: 12px;
        padding: 22px 20px;
    }
    .overview-card h4 {
        font-size: 0.95rem;
        font-weight: 700;
        margin: 0 0 12px 0;
    }
    .overview-card ul {
        margin: 0;
        padding-left: 18px;
    }
    .overview-card li {
        font-size: 0.83rem;
        line-height: 1.7;
        margin-bottom: 4px;
    }
    .ov-bg1 { background: #e8f0fe; border-left: 4px solid #1565c0; }
    .ov-bg1 h4 { color: #1565c0; }
    .ov-bg2 { background: #fce8e6; border-left: 4px solid #c62828; }
    .ov-bg2 h4 { color: #c62828; }
    .ov-bg3 { background: #e6f4ea; border-left: 4px solid #2e7d32; }
    .ov-bg3 h4 { color: #2e7d32; }
    </style>
    """, unsafe_allow_html=True)

    # ── Hero Banner ──────────────────────────────────────────────────────────
    st.markdown("""
    <div class="hero-banner">
        <div class="hero-accent"></div>
        <div class="hero-eyebrow">Precision Oncology &nbsp;·&nbsp; Multi-Omics &nbsp;·&nbsp; TCGA-LUAD</div>
        <div class="hero-title">LUAD Precision Oncology Platform</div>
        <div class="hero-subtitle">
            A 7-module multi-omics pipeline integrating somatic variant annotation,
            tumor microenvironment profiling, ESM2 protein language model embeddings,
            and evidence-based drug mapping for lung adenocarcinoma precision medicine.
        </div>
        <div class="badge-row">
            <span class="badge badge-blue">Python 3.10+</span>
            <span class="badge badge-green">ESM2-650M</span>
            <span class="badge badge-purple">PCGR v2.2.5</span>
            <span class="badge badge-orange">TCGA-LUAD</span>
            <span class="badge badge-teal">CIViC · NCCN/FDA</span>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Overview (plain markdown, no HTML cards) ─────────────────────────────
    st.markdown("---")
    st.markdown("""
### Overview

Lung adenocarcinoma (LUAD) is the most common subtype of non-small cell lung cancer (NSCLC),
accounting for approximately 40% of all lung cancer diagnoses worldwide and remaining one of
the leading causes of cancer-related mortality globally. Unlike many other cancer types that
respond to a single standard-of-care protocol, LUAD is driven by highly heterogeneous somatic
mutations — a patient harboring an *EGFR* exon 19 deletion responds dramatically to osimertinib,
while a patient with *STK11* loss may derive little benefit from PD-1 checkpoint immunotherapy
even when tumor mutational burden appears high. Identifying the precise molecular profile of
each patient is therefore not optional: it is the foundation of effective treatment selection.

**What does this platform do?**

This platform automatically processes each patient's somatic variant calls, bulk RNA-seq
expression data, and clinical metadata through 7 integrated analysis modules — producing a
structured precision medicine report that addresses four core clinical questions: who is this
patient (survival context, stage, demographics), what mutations does their tumor carry (somatic
variants, TMB, mutational signatures), how is their tumor behaving (gene expression outliers,
immune microenvironment composition, dysregulated pathways), and which treatments have evidence
of efficacy for their specific mutation profile (targeted therapy, immunotherapy, chemotherapy).

**Why was this platform built — pain points addressed**

Current clinical bioinformatics workflows are fragmented. A typical analysis requires running
Ensembl VEP for variant annotation, a separate script to compute TMB, a dedicated pathway tool
for enrichment analysis, and a manual review of NCCN guidelines and the CIViC database for drug
matching — often across five or more disconnected tools with no shared data schema. Integrating
results across these tools requires significant manual effort, is error-prone, and is not
reproducible without careful bookkeeping. This platform replaces the entire toolchain with a
single orchestration command (`python run_all.py`), with automatic inter-module dependency
handling and a unified output structure.

Beyond workflow integration, standard clinical pipelines classify mutations using rule-based
databases (e.g., ClinVar, OncoKB) that assign a pathogenicity label but cannot capture *how
structurally damaging* a mutation is at the protein level. This platform introduces an AI layer
using **ESM2-650M** (Meta AI's protein language model), which extracts 1280-dimensional
embeddings at each missense mutation site and computes masked-marginal log-odds scores —
quantifying the degree to which the mutation is unexpected given the evolutionary context of
the protein. These features enable downstream machine learning–based variant effect prediction
that goes beyond binary rule-based classification.

**Key technical innovations**

*End-to-end automation.* A single command orchestrates all 7 modules in dependency order, with
automatic failure handling. Module 02 (variant annotation) feeds into Module 05 (pathway
enrichment) and Module 07 (drug mapping); if an upstream module fails, dependent modules are
automatically skipped with a clear error message.

*ESM2 protein language model embeddings (Module 06).* For every missense mutation identified
in Module 02, the platform retrieves the canonical protein sequence from UniProt, runs
ESM2-650M inference, and extracts the per-site 1280-dimensional hidden state for both the
wild-type and mutant amino acid. The delta embedding (mutant minus wild-type) serves as a
structural perturbation proxy. These features can be directly fed into supervised classifiers
for pathogenicity prediction or used for unsupervised clustering of mutation types.

*GPT-4o + PubMed literature integration (Module 07).* For each actionable variant identified
in drug mapping, the platform automatically queries PubMed via the NCBI Entrez API for the
most relevant clinical literature, retrieves abstracts from the top papers, and uses GPT-4o
to generate a concise structured clinical summary — covering the mutation's known oncogenic
role, associated therapies, and clinical evidence level. This connects the analysis directly
to the latest published evidence without requiring manual literature review.

*Single-cell tumor microenvironment characterization (Module 04).* The platform integrates
the 57,000-cell Lung Cancer Cell Atlas (GSE131907) to quantify the composition of the tumor
immune microenvironment — including T cell, NK cell, macrophage, dendritic cell, and cancer
cell populations. Immune infiltration patterns are a critical determinant of immunotherapy
response and are rarely assessed in standard clinical bioinformatics pipelines.

*Clinically actionable drug report (Module 07).* All mutation findings are mapped to an
embedded NCCN/FDA-curated knowledge base covering 16 LUAD driver genes, supplemented by
live CIViC REST API queries for additional evidence. Immunotherapy eligibility is assessed
based on TMB threshold (≥10 mut/Mb) and STK11/KEAP1 resistance markers, producing a
report that directly answers which therapy regimen is supported by clinical evidence for
that patient.
    """)
    st.markdown("---")

    # ── Key Stats ────────────────────────────────────────────────────────────
    st.markdown("""
    <div class="stat-grid">
        <div class="stat-card" style="border-left-color:#1565c0;">
            <div class="stat-number">8</div>
            <div class="stat-label">Analysis Modules</div>
        </div>
        <div class="stat-card" style="border-left-color:#2e7d32;">
            <div class="stat-number">5</div>
            <div class="stat-label">TCGA-LUAD Samples</div>
        </div>
        <div class="stat-card" style="border-left-color:#6a1b9a;">
            <div class="stat-number">1280</div>
            <div class="stat-label">ESM2 Embedding Dims</div>
        </div>
        <div class="stat-card" style="border-left-color:#e65100;">
            <div class="stat-number">~20K</div>
            <div class="stat-label">Genes Covered (RNA-seq)</div>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Module Cards ─────────────────────────────────────────────────────────
    st.markdown('<div class="section-heading">Analysis Modules</div>', unsafe_allow_html=True)
    st.markdown("""
    <div class="module-grid">
        <div class="module-card">
            <span class="module-id">01</span>
            <span class="module-name">Patients</span>
            <div class="module-desc">GDC clinical data retrieval · Kaplan-Meier survival curves · patient summary card</div>
            <span class="module-tag">Clinical</span>
            <span class="module-tag">Survival</span>
        </div>
        <div class="module-card">
            <span class="module-id">02</span>
            <span class="module-name">Variants</span>
            <div class="module-desc">VEP/PCGR somatic annotation · tumor mutational burden (TMB) · SBS mutational spectrum</div>
            <span class="module-tag">Genomics</span>
            <span class="module-tag">TMB</span>
            <span class="module-tag">VEP</span>
        </div>
        <div class="module-card">
            <span class="module-id">03</span>
            <span class="module-name">Expression</span>
            <div class="module-desc">Bulk RNA-seq TPM normalization · cohort-level outlier gene detection · clinical gene panel</div>
            <span class="module-tag">RNA-seq</span>
            <span class="module-tag">Outlier</span>
        </div>
        <div class="module-card">
            <span class="module-id">04</span>
            <span class="module-name">Single-cell TME</span>
            <div class="module-desc">ssGSEA cell-type deconvolution · GSE131907 reference · immune phenotype (Inflamed / Excluded / Desert)</div>
            <span class="module-tag">scRNA</span>
            <span class="module-tag">Immune</span>
            <span class="module-tag">TME</span>
        </div>
        <div class="module-card">
            <span class="module-id" style="background:#6a1b9a;">05</span>
            <span class="module-name">Pathology</span>
            <div class="module-desc">H&E slide analysis · tissue segmentation · TIL density scoring · TME phenotype classification</div>
            <span class="module-tag" style="background:#f3e5f5;color:#6a1b9a;">Pathology</span>
            <span class="module-tag">H&amp;E</span>
            <span class="module-tag">TIL</span>
            <span class="module-tag">WSI</span>
        </div>
        <div class="module-card">
            <span class="module-id">06</span>
            <span class="module-name">Pathway</span>
            <div class="module-desc">Over-representation analysis (ORA) on mutated genes · GSEA prerank on expression fold-changes</div>
            <span class="module-tag">ORA</span>
            <span class="module-tag">GSEA</span>
        </div>
        <div class="module-card">
            <span class="module-id" style="background:#e65100;">07</span>
            <span class="module-name">ESM2</span>
            <div class="module-desc">Per-site 1280-dim protein embeddings · masked-marginal log-odds · variant effect prediction <em>(GPU recommended)</em></div>
            <span class="module-tag" style="background:#fff3e0;color:#e65100;">GPU</span>
            <span class="module-tag">ESM2</span>
            <span class="module-tag">Embeddings</span>
        </div>
        <div class="module-card">
            <span class="module-id" style="background:#1565c0;">08</span>
            <span class="module-name">Multi-modal Immune Activity Score</span>
            <div class="module-desc">CoxNet + XGBoost survival · all protein-coding genes · TIL density (M05) · driver mutations · multi-modal immune activity scoring</div>
            <span class="module-tag" style="background:#e3f2fd;color:#1565c0;">ML</span>
            <span class="module-tag">Immunotherapy</span>
            <span class="module-tag">Survival</span>
        </div>
        <div class="module-card">
            <span class="module-id" style="background:#2e7d32;">09</span>
            <span class="module-name">Multimodal Integration</span>
            <div class="module-desc">Multi-omics evidence integration · M02+M03+M04+M05+M08 · treatment confidence scoring</div>
            <span class="module-tag" style="background:#e8f5e9;color:#2e7d32;">Integration</span>
            <span class="module-tag">Multi-omics</span>
        </div>
        <div class="module-card">
            <span class="module-id" style="background:#b71c1c;">10</span>
            <span class="module-name">Clinical Recommendation</span>
            <div class="module-desc">OncoKB · AMP/ASCO/CAP · ESCAT evidence grading · ranked targeted / IO / combination therapy</div>
            <span class="module-tag" style="background:#ffebee;color:#b71c1c;">Clinical</span>
            <span class="module-tag">NCCN</span>
            <span class="module-tag">CIViC</span>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Sample Coverage Table ────────────────────────────────────────────────
    st.markdown('<div class="section-heading">Demo Samples</div>', unsafe_allow_html=True)
    _demo_ids = (SAMPLES[:5] if len(SAMPLES) >= 5
                 else SAMPLES + ["—"] * (5 - len(SAMPLES)))
    demo_data = {
        "Sample ID":  _demo_ids,
        "Variants":   ["✅", "✅", "—", "✅", "—"],
        "RNA-seq":    ["✅", "—", "✅", "—", "✅"],
        "Pathway":    ["✅", "✅", "✅", "✅", "✅"],
        "Drug Report":["✅", "✅", "—", "✅", "—"],
        "ESM2":       ["⏳ GPU", "—", "—", "—", "—"],
        "Pathology":  ["—", "—", "—", "—", "✅"],
    }
    st.dataframe(pd.DataFrame(demo_data), use_container_width=True, hide_index=True)

    # ── Quick Start ──────────────────────────────────────────────────────────
    st.markdown('<div class="section-heading">Quick Start</div>', unsafe_allow_html=True)
    st.code("""# Run full pipeline (all samples, skip ESM2)
python run_all.py

# Run a single sample
python run_all.py --sample TCGA-86-A4D0

# Include ESM2 inference (requires GPU)
python run_all.py --include_esm2

# Validate inputs without running analysis
python run_all.py --dry_run
""", language="bash")

    # ── Footer ───────────────────────────────────────────────────────────────
    st.divider()
    st.markdown("""
    <div style="text-align:center; color:#666; font-size:0.85rem; padding: 8px 0 16px 0;">
        Any questions please contact <strong>Yujuan Zhang, PhD</strong>
        &nbsp;·&nbsp;
        <a href="mailto:yujuan.zhang418@gmail.com" style="color:#1565c0; text-decoration:none;">
            yujuan.zhang418@gmail.com
        </a>
    </div>
    """, unsafe_allow_html=True)


# ══════════════════════════════════════════════════════════════════════════════
# 01 · PATIENT CONTEXT
# ══════════════════════════════════════════════════════════════════════════════

elif page == "01 · Patients":
    st.header("01 · Patients")
    st.caption("GDC clinical data · survival analysis · patient summary card")

    # M01 saves cards flat: 01_patients/{id}_patient_card.png (no subdirs)
    _m01_dir = OUTPUT / "01_patients"
    _m01_samples = sorted([
        f.stem.replace("_patient_card", "")
        for f in _m01_dir.glob("*_patient_card.png")
    ]) if _m01_dir.exists() else []
    if not _m01_samples:
        _m01_samples = discover_clinical_samples() or SAMPLES
    sample = st.selectbox("Patient", _m01_samples, key="sel_m01",
                          help=f"{len(_m01_samples)} patients available")

    # Patient card image
    img = OUTPUT / "01_patients" / f"{sample}_patient_card.png"
    show_image(img, caption=f"Patient summary card — {sample}")

    st.divider()

    # Clinical summary table (all samples)
    st.subheader("Cohort Clinical Summary")
    show_table(
        OUTPUT / "01_patients" / "clinical_summary.tsv",
        caption="All available samples · GDC clinical metadata",
    )


# ══════════════════════════════════════════════════════════════════════════════
# 02 · VARIATION ANNOTATION
# ══════════════════════════════════════════════════════════════════════════════

elif page == "02 · Variants":
    st.header("02 · Variants")
    st.caption("Somatic variants annotated with VEP/PCGR · tumor mutational burden · SBS spectrum")

    _m02_samples = discover_module_samples(OUTPUT / "02_variants", "_variants.tsv.gz")
    sample = st.selectbox("Patient", _m02_samples or SAMPLES, key="sel_m02",
                          help=f"{len(_m02_samples)} patients with variant output")

    # Variant summary image
    img = OUTPUT / "02_variants" / sample / f"{sample}_variant_summary.png"
    show_image(img, caption=f"Variant summary — {sample}")

    st.divider()

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Tumor Mutational Burden")
        show_table(
            OUTPUT / "02_variants" / sample / f"{sample}_tmb.tsv",
            caption="TMB metrics for this sample",
        )

    with col2:
        st.subheader("Cohort Summary")
        show_table(
            OUTPUT / "02_variants" / "all_samples_summary.tsv",
            caption="Cross-sample variant statistics",
        )

    st.divider()

    st.subheader("Somatic Variants")
    show_table(
        OUTPUT / "02_variants" / sample / f"{sample}_variants.tsv.gz",
        nrows=100,
        caption=f"Top 100 variants shown · {sample}",
    )


# ══════════════════════════════════════════════════════════════════════════════
# 03 · EXPRESSION ANALYSIS
# ══════════════════════════════════════════════════════════════════════════════

elif page == "03 · Expression":
    st.header("03 · Expression")
    st.caption("Bulk RNA-seq · GTEx normal lung baseline · per-patient & cohort-level figures")

    _m03_samples = discover_module_samples(OUTPUT / "03_expression", "_clinical_genes.png")
    sample = st.selectbox("Patient", _m03_samples or SAMPLES, key="sel_m03",
                          help=f"{len(_m03_samples)} patients with expression output")

    # ── Per-patient figures ───────────────────────────────────────────────────
    tab1, tab2, tab3 = st.tabs([
        "📊 Expression Summary",
        "🧬 Clinical Gene Panel",
        "🔬 Mutation–Expression",
    ])

    with tab1:
        show_image(
            OUTPUT / "03_expression" / sample / f"{sample}_expression_summary.png",
            caption=f"Expression outliers vs GTEx Normal Lung — {sample}",
        )
        st.divider()
        st.subheader("Expression Outlier Genes")
        st.caption("Genes with |GTEx Z-score| > 2 (tumor vs normal lung). First 200 rows.")
        outliers_tsv = OUTPUT / "03_expression" / sample / f"{sample}_expression_outliers.tsv.gz"
        if not outliers_tsv.exists():
            outliers_tsv = OUTPUT / "03_expression" / sample / f"{sample}_expression_outliers.tsv"
        if outliers_tsv.exists():
            show_table(outliers_tsv, nrows=200, caption=f"Outlier genes — {sample}")
        else:
            st.info("Detailed outlier table available in local pipeline output only.")
        st.divider()
        st.subheader("Cohort-level Overview")
        col1, col2 = st.columns(2)
        with col1:
            show_image(
                OUTPUT / "03_expression" / "cohort_clinical_genes_heatmap.png",
                caption="Clinical gene Z-scores — 517 patients × 21 genes",
            )
        with col2:
            show_image(
                OUTPUT / "03_expression" / "cohort_outlier_distribution.png",
                caption="Outlier gene counts per patient vs GTEx Normal Lung",
            )

    with tab2:
        show_image(
            OUTPUT / "03_expression" / sample / f"{sample}_clinical_genes.png",
            caption=f"LUAD clinical gene expression vs GTEx Normal Lung — {sample}",
        )

    with tab3:
        mut_img = OUTPUT / "03_expression" / sample / f"{sample}_mutation_expression.png"
        if mut_img.exists():
            show_image(mut_img,
                       caption=f"Mutated gene expression positions — {sample}")
        else:
            st.info("No mutation data available for this patient (M02 output not found).")


# ══════════════════════════════════════════════════════════════════════════════
# 04 · SINGLE-CELL TME  (sample-independent)
# ══════════════════════════════════════════════════════════════════════════════

elif page == "04 · Single-Cell TME":
    st.header("04 · Single-Cell Tumor Microenvironment")
    st.caption("Stage 1: GSE131907 single-cell reference · Stage 2: ssGSEA deconvolution of TCGA bulk RNA-seq")

    tab1, tab2 = st.tabs(["Cohort TME (ssGSEA)", "Single-Cell Reference (GSE131907)"])

    # ── Tab 1: ssGSEA cohort deconvolution ──────────────────────────────────────
    with tab1:
        st.subheader("TCGA-LUAD Immune Phenotype Distribution")

        cohort_scores_path = OUTPUT / "04_single_cell" / "tme_cohort_scores.tsv"
        if cohort_scores_path.exists():
            df_tme = pd.read_csv(cohort_scores_path, sep="\t")

            # Phenotype summary metrics
            if "immune_phenotype" in df_tme.columns:
                n_total = len(df_tme)
                pc = df_tme["immune_phenotype"].value_counts()
                c1, c2, c3 = st.columns(3)
                colors_map = {"Inflamed": "🟢", "Excluded": "🟡", "Desert": "🔴"}
                for col, ptype in zip([c1, c2, c3], ["Inflamed", "Excluded", "Desert"]):
                    n = pc.get(ptype, 0)
                    col.metric(
                        f"{colors_map.get(ptype,'⚪')} {ptype}",
                        f"{n}",
                        f"{100*n/n_total:.0f}% of cohort",
                    )

            st.divider()

            # Cohort heatmap
            show_image(
                OUTPUT / "04_single_cell" / "tme_cohort_heatmap.png",
                caption="Cohort TME heatmap — ssGSEA enrichment scores × 517 TCGA-LUAD patients",
            )

            st.divider()

            # Per-patient selector
            st.subheader("Per-Patient TME Profile")
            _m04_samples = patients_for_page("04 · Single-Cell TME")
            if _m04_samples:
                sel_sample = st.selectbox(
                    "Select patient", _m04_samples,
                    key="m04_sample",
                    index=_m04_samples.index("TCGA-86-A4D0") if "TCGA-86-A4D0" in _m04_samples else 0,
                )
                tme_path = OUTPUT / "04_single_cell" / sel_sample / f"{sel_sample}_tme_scores.tsv"
                if tme_path.exists():
                    df_pat = pd.read_csv(tme_path, sep="\t")
                    cell_cols = [c for c in df_pat.columns if c not in ("sample_id", "immune_phenotype")]
                    phenotype = df_pat["immune_phenotype"].iloc[0] if "immune_phenotype" in df_pat.columns else "Unknown"

                    # Phenotype badge
                    ph_info = {
                        "Inflamed": ("🟢", "High immune infiltration — potential IO responder"),
                        "Excluded": ("🟡", "Immune cells confined to stroma — partial IO resistance"),
                        "Desert":   ("🔴", "Low immune infiltration — IO likely ineffective"),
                    }
                    icon, desc = ph_info.get(phenotype, ("⚪", ""))
                    st.info(f"**{icon} TME Phenotype: {phenotype}** — {desc}")

                    # Bar chart of ssGSEA scores
                    import matplotlib.pyplot as plt
                    scores_row = df_pat[cell_cols].iloc[0]
                    fig_bar, ax_bar = plt.subplots(figsize=(9, 3.5))
                    bars = ax_bar.bar(cell_cols, scores_row.values, color="#4e79a7", edgecolor="white")
                    ax_bar.set_ylabel("ssGSEA Enrichment Score")
                    ax_bar.set_title(f"TME Cell-Type Profile — {sel_sample}")
                    ax_bar.set_xticklabels(cell_cols, rotation=35, ha="right", fontsize=9)
                    fig_bar.tight_layout()
                    st.pyplot(fig_bar)
                    plt.close(fig_bar)
                else:
                    st.info("Per-patient TME file not found. Run module 04 locally.")

            st.divider()

            # Full cohort table
            with st.expander("Full Cohort ssGSEA Scores Table"):
                show_table(cohort_scores_path, nrows=520, caption="ssGSEA scores — all 517 TCGA-LUAD patients")
        else:
            st.info("Cohort TME scores not yet generated. Run: `python modules/04_single_cell/luad_singlecell.py --skip_sc`")

    # ── Tab 2: GSE131907 single-cell reference ───────────────────────────────────
    with tab2:
        st.subheader("GSE131907 Single-Cell Reference (Kim et al. 2020)")
        st.caption("58 tLung samples · cell-type fractions · immune phenotype classification")

        show_image(
            OUTPUT / "04_single_cell" / "luad_tme_overview.png",
            caption="GSE131907 Lung Cancer Cell Atlas — TME overview",
        )

        st.divider()

        col1, col2 = st.columns(2)
        with col1:
            st.subheader("Per-Sample Immune Metrics")
            show_table(
                OUTPUT / "04_single_cell" / "per_sample_immune_metrics.tsv",
                caption="Immune score, stromal score, estimate score",
            )
        with col2:
            st.subheader("Cell-Type Fractions")
            show_table(
                OUTPUT / "04_single_cell" / "per_sample_tme_fractions.tsv",
                caption="Relative abundance of each TME cell type",
            )

        st.divider()
        st.subheader("TME Summary")
        show_table(
            OUTPUT / "04_single_cell" / "luad_tme_summary.tsv",
            caption="Cohort-level TME summary statistics",
        )


# ══════════════════════════════════════════════════════════════════════════════
# 05 · PATHWAY ENRICHMENT
# ══════════════════════════════════════════════════════════════════════════════

elif page == "06 · Pathway":
    st.header("06 · Pathway")
    st.caption("KEGG pathway viewer · ORA on mutated genes · GSEA prerank on expression")

    _m05_gsea = discover_module_samples(OUTPUT / "06_pathway", "_gsea.tsv")
    _m05_ora  = discover_module_samples(OUTPUT / "06_pathway", "_ora.tsv")
    _m05_samples = sorted(set(_m05_gsea) | set(_m05_ora))
    sample = st.selectbox("Patient", _m05_samples or SAMPLES, key="sel_m05",
                          help=f"{len(_m05_samples)} patients with pathway output ({len(_m05_gsea)} with GSEA)")

    # ── KEGG Pathway Viewer ────────────────────────────────────────────────────
    st.subheader("KEGG Pathway View")
    st.caption("🔴 Mutated · 🟠 High expression (z > 1.5) · 🔵 Low expression (z < −1.5)")

    import sys
    sys.path.insert(0, str(Path(__file__).parent / "modules" / "06_pathway"))
    from kegg_viewer import (
        LUAD_PATHWAYS, load_all_pathway_genes, get_hit_pathways,
        load_mutations, load_expression_colors, build_kegg_url,
        build_gene_table, render_pathway,
    )
    _KEGG_CACHE = Path(__file__).parent / "modules" / "06_pathway" / "kegg_cache" / "pathways"

    @st.cache_data(show_spinner="Loading KEGG gene sets…", ttl=86400)
    def _load_pathway_genes():
        return load_all_pathway_genes()

    pathway_genes = _load_pathway_genes()
    mutations     = load_mutations(sample)

    if not mutations:
        st.info(f"No variant data found for {sample}. KEGG viewer requires M02 output.")
    else:
        hit_pathways = get_hit_pathways(mutations, pathway_genes)

        # ── Overview bar chart ─────────────────────────────────────────────────
        import matplotlib.pyplot as plt
        all_names = list(LUAD_PATHWAYS.keys())
        hit_dict  = {name: len(hits) for name, _, hits in hit_pathways}

        fig, ax = plt.subplots(figsize=(8, 3.5))
        bar_colors = ["#d62728" if hit_dict.get(n, 0) > 0 else "#cccccc"
                      for n in all_names]
        bars = ax.bar(all_names, [hit_dict.get(n, 0) for n in all_names],
                      color=bar_colors, edgecolor="white", width=0.6)
        ax.set_ylabel("Mutated genes in pathway", fontsize=9)
        ax.set_title(f"LUAD Pathway Hit Summary — {sample}", fontsize=10, fontweight="bold")
        ax.set_xticks(range(len(all_names)))
        ax.set_xticklabels(all_names, rotation=30, ha="right", fontsize=8)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        for bar, n in zip(bars, all_names):
            v = hit_dict.get(n, 0)
            if v > 0:
                ax.text(bar.get_x() + bar.get_width() / 2, v + 0.05,
                        str(v), ha="center", va="bottom", fontsize=9, fontweight="bold")
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

        if not hit_pathways:
            st.info("No mutations fall within the 8 core LUAD pathways for this patient.")

        # ── Manual pathway selector ────────────────────────────────────────────
        hit_names   = [h[0] for h in hit_pathways]
        other_names = [n for n in all_names if n not in hit_names]
        extra = st.multiselect(
            "Add more pathways to view",
            options=other_names, default=[], key="kegg_extra",
        )

        display_pathways = hit_pathways.copy()
        for name in extra:
            pid = LUAD_PATHWAYS[name][0]
            display_pathways.append((name, pid, []))

        # ── Per-pathway detail ─────────────────────────────────────────────────
        for name, pid, hit_genes in display_pathways:
            pg         = pathway_genes.get(pid, [])
            high, low  = load_expression_colors(sample, pg)
            kegg_url   = build_kegg_url(pid, mutations, high, low)
            gene_table = build_gene_table(sample, pg, mutations, high, low)

            n_mut  = len(hit_genes)
            n_high = len([g for g in high if g not in {x.upper() for x in hit_genes}])
            n_low  = len([g for g in low  if g not in {x.upper() for x in hit_genes}])
            label  = (f"🔴 **{name}** — {n_mut} mutated"
                      + (f", {n_high} ↑" if n_high else "")
                      + (f", {n_low} ↓"  if n_low  else ""))

            with st.expander(label, expanded=bool(hit_genes)):
                png_bytes = render_pathway(pid, mutations, high, low,
                                           cache_dir=_KEGG_CACHE)
                if png_bytes:
                    st.image(png_bytes, use_container_width=True)
                    st.link_button(f"Open in KEGG ↗", url=kegg_url)
                else:
                    st.warning(f"Cache not found: {_KEGG_CACHE / pid}.png")
                    st.link_button(
                        f"Open {name} in KEGG ↗", url=kegg_url,
                        help="Local image not available — opens KEGG website",
                    )
                if not gene_table.empty:
                    st.markdown("**Genes hit in this patient:**")
                    st.dataframe(gene_table, use_container_width=True, hide_index=True)
                elif hit_genes:
                    st.markdown(f"Mutated: `{'`, `'.join(hit_genes)}`")

    st.divider()

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("GSEA Results")
        show_table(
            OUTPUT / "06_pathway" / sample / f"{sample}_gsea.tsv",
            caption=f"Top enriched gene sets (GSEA prerank) — {sample}",
        )

    with col2:
        st.subheader("ORA Results")
        show_table(
            OUTPUT / "06_pathway" / sample / f"{sample}_ora.tsv",
            caption=f"Over-represented pathways (ORA) — {sample}",
        )

    st.divider()

    # ── Cross-sample pathway frequency ────────────────────────────────────────
    st.subheader("Cross-Sample Pathway Summary")
    st.caption("Pathways ranked by how many patients show significant activation (GSEA FDR < 0.25, NES > 0). "
               "Housekeeping pathways activated in >90% of patients are excluded.")

    summary_path = OUTPUT / "06_pathway" / "all_samples_summary.tsv"
    if summary_path.exists():
        import matplotlib.pyplot as plt

        pw_df = pd.read_csv(summary_path, sep="\t")

        luad_only = st.checkbox("Show LUAD-relevant pathways only", value=False)
        if luad_only:
            pw_df = pw_df[pw_df["luad_relevant"] == True]

        top_n = st.slider("Number of pathways to display", 10, 50, 20)
        plot_df = pw_df.head(top_n).sort_values("pct_patients")

        fig, ax = plt.subplots(figsize=(9, max(4, len(plot_df) * 0.38)))
        colors = ["#2ca02c" if r else "#4393c3"
                  for r in plot_df["luad_relevant"]]
        bars = ax.barh(plot_df["pathway"], plot_df["pct_patients"],
                       color=colors, alpha=0.85, edgecolor="white")
        ax.set_xlabel("% Patients Activated (NES > 0, FDR < 0.25)", fontsize=10)
        ax.set_title(f"Top {top_n} Most Commonly Activated Pathways — LUAD Cohort (n={len(pw_df.dropna())})",
                     fontsize=10)
        ax.axvline(50, color="gray", linestyle="--", linewidth=0.8, alpha=0.6)
        for bar, val in zip(bars, plot_df["pct_patients"]):
            ax.text(val + 0.5, bar.get_y() + bar.get_height() / 2,
                    f"{val:.0f}%", va="center", fontsize=8)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        from matplotlib.patches import Patch
        ax.legend(handles=[Patch(color="#2ca02c", label="LUAD-relevant"),
                            Patch(color="#4393c3", label="Other")],
                  fontsize=8, loc="lower right")
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

        with st.expander("View full table"):
            st.dataframe(pw_df[["pathway", "n_activated", "n_suppressed",
                                 "pct_patients", "mean_nes", "luad_relevant"]],
                         use_container_width=True)
    else:
        st.info("Run `python modules/06_pathway/luad_pathway.py --summarize` to generate cross-sample summary.")


# ══════════════════════════════════════════════════════════════════════════════
# 07 · Variant Impact
# ══════════════════════════════════════════════════════════════════════════════

elif page == "07 · Variant Impact":
    st.header("07 · Variant Impact")
    st.caption("AlphaMissense pathogenicity scoring · missense mutation functional impact")

    import pandas as pd
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    import numpy as np
    import re as _re

    # ── Lollipop plot helper ───────────────────────────────────────────────────
    # Protein lengths (UniProt canonical isoform)
    _PROTEIN_LEN = {
        "KRAS":189, "NRAS":189, "HRAS":189,
        "EGFR":1210, "ERBB2":1255, "MET":1390, "ALK":1620, "ROS1":2347,
        "RET":1114, "FGFR1":822, "FGFR2":821, "FGFR3":806, "FGFR4":802,
        "TP53":393, "RB1":928, "CDKN2A":156,
        "BRAF":766, "RAF1":648, "MAP2K1":393, "MAP2K2":400,
        "PIK3CA":1068, "PTEN":403, "AKT1":480,
        "STK11":433, "KEAP1":624, "NF1":2839,
        "MYC":439, "MYCL":364, "MYCN":464,
        "SMARCA4":1647, "ARID1A":2285, "SETD2":2564, "RBM10":930,
    }
    # Key functional domains {gene: [(start, end, label, color), ...]}
    _DOMAINS = {
        "KRAS": [
            (10, 17, "P-loop",    "#aec6cf"),
            (30, 38, "Switch I",  "#77dd77"),
            (58, 76, "Switch II", "#fdfd96"),
        ],
        "EGFR": [
            (712, 979, "Kinase domain", "#aec6cf"),
            (25,  645, "Extracellular", "#fdfd96"),
        ],
        "TP53": [
            (1,   43,  "Transactivation", "#fdfd96"),
            (102, 292, "DNA-binding",     "#aec6cf"),
            (323, 356, "Tetramerization", "#77dd77"),
        ],
        "BRAF": [
            (155, 227, "RBD",            "#fdfd96"),
            (457, 717, "Kinase domain",  "#aec6cf"),
        ],
        "PIK3CA": [
            (726, 1068, "Kinase domain", "#aec6cf"),
            (515,  696, "Helical",       "#fdfd96"),
        ],
        "STK11": [(49, 309, "Kinase domain", "#aec6cf")],
        "MET":   [(956, 1382, "Kinase domain", "#aec6cf")],
        "RET":   [(713, 1013, "Kinase domain", "#aec6cf")],
        "ALK":   [(1122, 1426, "Kinase domain", "#aec6cf")],
        "ROS1":  [(1882, 2222, "Kinase domain", "#aec6cf")],
        "PTEN":  [(14, 185, "Phosphatase", "#aec6cf")],
        "NF1":   [(1198, 1530, "RasGAP domain", "#aec6cf")],
    }

    def _parse_pos(hgvsp: str):
        m = _re.match(r"p\.([A-Z])(\d+)([A-Z*])", str(hgvsp))
        return (int(m.group(2)), m.group(1), m.group(3)) if m else (None, None, None)

    def _lollipop(gene: str, gene_df: pd.DataFrame) -> plt.Figure:
        prot_len = _PROTEIN_LEN.get(gene, None)
        domains  = _DOMAINS.get(gene, [])

        positions, scores, classes, labels = [], [], [], []
        for _, row in gene_df.iterrows():
            pos, wt, mut = _parse_pos(row["hgvsp"])
            if pos is None:
                continue
            positions.append(pos)
            scores.append(float(row["am_pathogenicity"]) if pd.notna(row["am_pathogenicity"]) else 0)
            classes.append(str(row["am_class"]))
            labels.append(f"{wt}{pos}{mut}")

        if not positions:
            return None

        xmax = max(prot_len or max(positions), max(positions)) + 10

        fig, ax = plt.subplots(figsize=(max(8, xmax / 100), 4))

        # Domain backgrounds
        for (ds, de, dlabel, dcolor) in domains:
            ax.axvspan(ds, de, alpha=0.25, color=dcolor, zorder=0)
            ax.text((ds + de) / 2, 1.02, dlabel, ha="center", va="bottom",
                    fontsize=7, color="#555", transform=ax.get_xaxis_transform())

        # Threshold lines
        ax.axhline(0.564, color="#d73027", lw=0.8, linestyle="--", alpha=0.6, label="Pathogenic (0.564)")
        ax.axhline(0.340, color="#4575b4", lw=0.8, linestyle="--", alpha=0.6, label="Benign (0.340)")

        # Lollipops
        color_map = {"pathogenic": "#d73027", "ambiguous": "#f4a261", "benign": "#4575b4"}
        for pos, score, cls, lbl in zip(positions, scores, classes, labels):
            c = color_map.get(cls, "#999")
            ax.vlines(pos, 0, score, colors=c, linewidth=1.8, zorder=2)
            ax.scatter(pos, score, color=c, s=60, zorder=3, edgecolors="white", linewidths=0.5)
            if score >= 0.564:
                ax.annotate(lbl, (pos, score), xytext=(0, 6),
                            textcoords="offset points", ha="center",
                            fontsize=7.5, color=c, fontweight="bold")

        ax.set_xlim(0, xmax)
        ax.set_ylim(-0.05, 1.2)
        ax.set_xlabel("Amino acid position", fontsize=9)
        ax.set_ylabel("AlphaMissense score", fontsize=9)
        ax.set_title(f"{gene}  —  mutation pathogenicity map", fontsize=10)
        ax.spines[["top", "right"]].set_visible(False)
        patches = [mpatches.Patch(color=v, label=k.capitalize()) for k, v in color_map.items()]
        ax.legend(handles=patches, fontsize=8, loc="upper right")
        plt.tight_layout()
        return fig

    # ── 选项1：队列总览柱状图 ─────────────────────────────────────────────────
    @st.cache_data(show_spinner="Loading cohort summary…", ttl=3600)
    def _load_cohort_am():
        summary_path = OUTPUT / "07_variant_impact" / "alphamissense_summary.tsv"
        if not summary_path.exists():
            return pd.DataFrame()
        # Load all per-patient files and aggregate by gene
        files = list((OUTPUT / "07_variant_impact").glob("*/*_alphamissense.tsv"))
        if not files:
            return pd.DataFrame()
        dfs = []
        for f in files:
            try:
                dfs.append(pd.read_csv(f, sep="\t"))
            except Exception:
                pass
        if not dfs:
            return pd.DataFrame()
        return pd.concat(dfs, ignore_index=True)

    cohort_df = _load_cohort_am()

    if not cohort_df.empty:
        st.subheader("Cohort Overview — Pathogenic Variants in Cancer Genes")
        st.caption(f"Across {cohort_df['sample_id'].nunique()} patients with AlphaMissense scores")

        # Count patients with ≥1 pathogenic mutation per gene
        path_df = cohort_df[cohort_df["am_class"] == "pathogenic"]
        gene_counts = (
            path_df.groupby("gene")["sample_id"]
            .nunique()
            .sort_values(ascending=False)
            .head(20)
        )

        fig, ax = plt.subplots(figsize=(10, 5))
        colors = ["#d73027" if g in [
            "KRAS","EGFR","TP53","STK11","KEAP1","BRAF","MET","ERBB2","NF1",
            "CDKN2A","RB1","PIK3CA","PTEN","ALK","ROS1","RET","MAP2K1","NRAS","HRAS","MYC"
        ] else "#4575b4" for g in gene_counts.index]
        bars = ax.bar(range(len(gene_counts)), gene_counts.values, color=colors, edgecolor="white", linewidth=0.5)
        ax.set_xticks(range(len(gene_counts)))
        ax.set_xticklabels(gene_counts.index, rotation=45, ha="right", fontsize=10)
        ax.set_ylabel("Number of patients", fontsize=10)
        ax.set_title("Top 20 genes with AlphaMissense-pathogenic mutations", fontsize=11)
        ax.spines[["top","right"]].set_visible(False)
        red_patch  = mpatches.Patch(color="#d73027", label="LUAD driver gene")
        blue_patch = mpatches.Patch(color="#4575b4", label="Other cancer gene")
        ax.legend(handles=[red_patch, blue_patch], fontsize=9)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

    st.divider()

    # ── 病人选择器 ────────────────────────────────────────────────────────────
    _m07_samples = discover_module_samples(OUTPUT / "07_variant_impact", "_alphamissense.tsv")
    sample = st.selectbox("Patient", _m07_samples or SAMPLES, key="sel_m07",
                          help=f"{len(_m07_samples)} patients with AlphaMissense scores")

    am_path = OUTPUT / "07_variant_impact" / sample / f"{sample}_alphamissense.tsv"
    if not am_path.exists():
        st.info("No AlphaMissense scores yet for this patient.")
    else:
        am_df = pd.read_csv(am_path, sep="\t")

        # Summary metrics
        n_total    = len(am_df)
        n_path     = (am_df["am_class"] == "pathogenic").sum()
        n_drv_path = int(((am_df["am_class"] == "pathogenic") & am_df["is_luad_driver"]).sum())
        c1, c2, c3 = st.columns(3)
        c1.metric("Scored mutations", n_total)
        c2.metric("Pathogenic", int(n_path))
        c3.metric("Pathogenic in driver genes", n_drv_path)

        st.divider()

        # ── Pathogenic driver gene table ──────────────────────────────────────
        drv_path = am_df[(am_df["am_class"] == "pathogenic") & am_df["is_luad_driver"]]
        if not drv_path.empty:
            st.subheader("Pathogenic mutations in LUAD driver genes")
            st.dataframe(
                drv_path[["gene","hgvsp","am_pathogenicity","am_class","existing_class","civic_level"]]
                .sort_values("am_pathogenicity", ascending=False)
                .reset_index(drop=True),
                use_container_width=True,
            )

        st.divider()

        # ── Lollipop plots ────────────────────────────────────────────────────
        genes_with_data = am_df["gene"].unique().tolist()
        # Show driver genes first, then others
        driver_genes = [g for g in genes_with_data if am_df[am_df["gene"]==g]["is_luad_driver"].any()]
        other_genes  = [g for g in genes_with_data if g not in driver_genes]
        ordered_genes = driver_genes + other_genes

        if ordered_genes:
            st.subheader("Mutation Position Map")
            st.caption("Each dot = one mutation. Height = AlphaMissense pathogenicity score. Red = pathogenic.")
            gene_sel = st.selectbox("Select gene", ordered_genes, key="lollipop_gene")
            gene_df  = am_df[am_df["gene"] == gene_sel]
            fig_lol  = _lollipop(gene_sel, gene_df)
            if fig_lol:
                st.pyplot(fig_lol)
                plt.close()
            else:
                st.info("No parseable HGVSp variants for this gene.")

        with st.expander("All scored mutations"):
            st.dataframe(
                am_df[["gene","hgvsp","am_pathogenicity","am_class","is_luad_driver"]]
                .sort_values("am_pathogenicity", ascending=False)
                .reset_index(drop=True),
                use_container_width=True,
            )


# ══════════════════════════════════════════════════════════════════════════════
# (07 · Drug Mapping — internal layer, not shown in sidebar)
# ══════════════════════════════════════════════════════════════════════════════

elif page == "07 · Drug Mapping":
    st.header("07 · Drug Mapping")
    st.caption("NCCN/FDA guidelines · CIViC evidence · therapy recommendations")

    # Cross-sample heatmap — square image, center at 55% width
    st.subheader("Drug Actionability — All Samples")
    img_heatmap = OUTPUT / "07_drug_mapping" / "drug_actionability_heatmap.png"
    _, mid, _ = st.columns([0.225, 0.55, 0.225])
    with mid:
        show_image(img_heatmap, caption="Drug actionability heatmap — all samples × genes")

    st.divider()

    # Per-sample selector — discover all samples that have a drug report file
    drug_samples = discover_module_samples(OUTPUT / "07_drug_mapping", "_drug_report.tsv")

    st.subheader("Per-Sample Drug Report")
    if not drug_samples:
        st.info("No drug reports found. Run `python run_all.py --modules 02 07` to generate them.")
        st.stop()

    st.caption(
        f"Drug reports available for {len(drug_samples)} samples."
    )
    selected = st.selectbox(
        "Select sample",
        options=drug_samples,
        index=0,
        key="drug_sample",
    )

    img_report = OUTPUT / "07_drug_mapping" / selected / f"{selected}_drug_report.png"
    show_image(img_report, caption=f"Drug report — {selected}")

    show_table(
        OUTPUT / "07_drug_mapping" / selected / f"{selected}_drug_report.tsv",
        caption=f"Recommended therapies — {selected}",
    )

    st.divider()

    st.subheader("Cross-Sample Drug Summary")
    show_table(
        OUTPUT / "07_drug_mapping" / "all_samples_drug_summary.tsv",
        caption="Drug recommendations across all samples",
    )

    st.divider()

    # LUAD drug context
    with st.expander("LUAD Targeted Therapy Reference (NCCN/FDA)"):
        st.markdown("""
        | Gene / Alteration | Drug(s) | Evidence |
        |-------------------|---------|----------|
        | EGFR exon 19 del / L858R | Osimertinib (1st line) | FDA approved |
        | EGFR T790M (resistance) | Osimertinib | FDA approved |
        | EGFR exon 20 ins | Amivantamab + Lazertinib | FDA approved |
        | ALK fusion | Alectinib / Lorlatinib | FDA approved |
        | ROS1 fusion | Crizotinib / Entrectinib | FDA approved |
        | RET fusion | Selpercatinib | FDA approved |
        | MET exon 14 skip | Capmatinib / Tepotinib | FDA approved |
        | BRAF V600E | Dabrafenib + Trametinib | FDA approved |
        | KRAS G12C | Sotorasib / Adagrasib | FDA approved |
        | NTRK fusion | Entrectinib / Larotrectinib | FDA approved |
        | HER2 mutation | Trastuzumab deruxtecan | FDA approved |
        | TMB ≥10 mut/Mb | Pembrolizumab (IO) | FDA approved |
        | STK11 loss | IO resistance — prefer chemo | NCCN note |
        """)


# ══════════════════════════════════════════════════════════════════════════════
# 05 · PATHOLOGY
# ══════════════════════════════════════════════════════════════════════════════

elif page == "05 · Pathology":
    st.header("05 · Pathology")
    st.caption("H&E slide analysis · tissue segmentation · TIL scoring · TME phenotype")

    st.markdown("""
    **What this module does:**

    Analyzes H&E-stained whole slide image (WSI) thumbnails downloaded from GDC using
    classical computer vision (no GPU required):

    1. **Tissue segmentation** — Otsu thresholding to separate tissue from background
    2. **H&E color deconvolution** — separate hematoxylin (nuclei) and eosin (cytoplasm) channels
    3. **Nuclear density** — estimate tumor cellularity from nuclear staining intensity
    4. **TIL scoring** — quantify tumor-infiltrating lymphocyte density (small dark nuclei)
    5. **TME phenotype** — classify as **Inflamed** / **Excluded** / **Desert**
    """)

    st.divider()

    # ── Cohort-level summary ─────────────────────────────────────────────────
    summary_path = OUTPUT / "05_pathology" / "pathology_summary.tsv"
    if summary_path.exists():
        st.subheader("Cohort Pathology Summary")
        df_summary = pd.read_csv(summary_path, sep="\t")

        # TME phenotype distribution
        col1, col2, col3 = st.columns(3)
        tme_counts = df_summary["tme_phenotype"].value_counts() if "tme_phenotype" in df_summary.columns else {}
        tme_colors = {"Inflamed": "🟢", "Excluded": "🟡", "Desert": "🔴"}
        for col, phenotype in zip([col1, col2, col3], ["Inflamed", "Excluded", "Desert"]):
            count = tme_counts.get(phenotype, 0)
            pct   = count / len(df_summary) * 100 if len(df_summary) > 0 else 0
            col.metric(
                label=f"{tme_colors.get(phenotype, '⚪')} {phenotype}",
                value=f"{count}",
                delta=f"{pct:.0f}% of slides",
            )

        st.dataframe(df_summary, use_container_width=True, hide_index=True)
    else:
        st.info(
            "No cohort summary yet. Run M08 to generate:\n"
            "```bash\npython modules/05_pathology/luad_pathology.py\n```"
        )

    st.divider()

    # ── Per-sample pathology report ──────────────────────────────────────────
    st.subheader("Per-Sample Pathology Report")

    # Discover which samples have pathology results
    path_out = OUTPUT / "05_pathology"
    available = sorted([
        d.name for d in path_out.iterdir()
        if d.is_dir() and (d / f"{d.name}_pathology_report.png").exists()
    ]) if path_out.exists() else []

    if available:
        selected_path = st.selectbox(
            "Select sample",
            options=available,
            index=0,
        )

        report_png   = path_out / selected_path / f"{selected_path}_pathology_report.png"
        scores_tsv   = path_out / selected_path / f"{selected_path}_pathology_scores.tsv"

        # Report figure
        show_image(report_png, caption=f"Pathology report — {selected_path}")

        # Scores table
        if scores_tsv.exists():
            st.subheader("Quantitative Scores")
            df_scores = pd.read_csv(scores_tsv, sep="\t")
            # Drop internal columns
            display_cols = [c for c in df_scores.columns if not c.startswith("_")]
            st.dataframe(df_scores[display_cols], use_container_width=True, hide_index=True)

            # Highlight TME phenotype
            if "tme_phenotype" in df_scores.columns:
                tme = df_scores["tme_phenotype"].iloc[0]
                tme_info = {
                    "Inflamed":  ("🟢", "High immune infiltration — potential IO responder"),
                    "Excluded":  ("🟡", "Immune cells present but confined to stroma — partial IO resistance"),
                    "Desert":    ("🔴", "Low immune infiltration — IO likely ineffective"),
                }
                icon, desc = tme_info.get(tme, ("⚪", ""))
                st.info(f"**{icon} TME Phenotype: {tme}** — {desc}")
    else:
        st.info(
            "No pathology reports generated yet.\n\n"
            "**Step 1:** Download WSI thumbnails:\n"
            "```bash\npython data/scripts/download_wsi.py --thumbnail --test\n```\n\n"
            "**Step 2:** Run M08 analysis:\n"
            "```bash\npython modules/05_pathology/luad_pathology.py\n```"
        )

    st.divider()

    # TME × Molecular cross-reference
    with st.expander("TME Phenotype — Clinical Significance"):
        st.markdown("""
        | TME Phenotype | Cohort Rank | IO Response | Recommended Strategy |
        |---------------|-------------|-------------|----------------------|
        | **Inflamed** | Top 30% TIL density | Likely responder | Pembrolizumab / Atezolizumab |
        | **Excluded** | Middle 50% TIL density | Partial resistance | IO + anti-VEGF combination |
        | **Desert** | Bottom 20% TIL density | Unlikely responder | Targeted therapy / Chemotherapy |

        Classification uses cohort-wide percentile thresholds (70th / 20th percentile of TIL density),
        not fixed absolute values. Cross-reference with M04 (single-cell TME) for integrated
        treatment decision support.
        """)


# ══════════════════════════════════════════════════════════════════════════════
# 09 · MULTIMODAL INTEGRATION
# ══════════════════════════════════════════════════════════════════════════════

elif page == "09 · Multimodal Integration":
    st.header("09 · Multimodal Integration")
    st.caption(
        "Multi-omics evidence integration · M02 somatic variants + M03 expression + "
        "M04 ssGSEA TME + M05 TIL + M08 Immune Activity Score · "
        "OncoKB / AMP-ASCO-CAP / ESCAT evidence grading · confidence 0–100"
    )

    with st.expander("Integration framework (click to expand)"):
        c1, c2 = st.columns(2)
        with c1:
            st.markdown("""
**Evidence sources per recommendation**
- **Targeted therapy**: M02 variant (VAF, clonality) + M07 drug mapping + M03 target expression + CIViC resistance
- **Immunotherapy**: TMB (M02) + TME phenotype (M04/M08) + PD-L1 RNA proxy + IFN-γ signature + TIDE score
- **Combination**: Co-mutation context + TME remodelling rationale
- **Chemotherapy**: Standard fallback with TMB/TME context
""")
        with c2:
            st.markdown("""
**Evidence grading system**
| Tier | Meaning |
|------|---------|
| OncoKB Level 1 / AMP Tier I-A | FDA-approved, same cancer type |
| OncoKB Level 2 / AMP Tier I-B | FDA-approved, different cancer |
| OncoKB Level 3A / ESCAT Tier V | Investigational / combination |
| Confidence 0–100 | Data-layer weighted score |
""")

    st.divider()

    # ── Cohort summary ────────────────────────────────────────────────────────
    summary_path = OUTPUT / "09_integration" / "integration_summary.tsv"
    if summary_path.exists():
        st.subheader("Cohort Integration Summary")
        df_sum = pd.read_csv(summary_path, sep="\t")

        # Top-level metrics
        n = len(df_sum)
        n_targeted  = (df_sum["n_targeted"] > 0).sum() if "n_targeted" in df_sum.columns else 0
        n_tmb_high  = df_sum["tmb_high"].sum()           if "tmb_high"  in df_sum.columns else 0
        n_combo     = (df_sum["n_combination"] > 0).sum() if "n_combination" in df_sum.columns else 0
        mean_io     = df_sum["io_score"].mean()           if "io_score"  in df_sum.columns else 0

        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Total Patients",       n)
        col2.metric("With Targeted Drugs",  f"{n_targeted} ({n_targeted/n:.0%})")
        col3.metric("High TMB (≥10 mut/Mb)",f"{n_tmb_high} ({n_tmb_high/n:.0%})")
        col4.metric("Mean IO Score",        f"{mean_io:.1f} / 100")

        col5, col6, col7 = st.columns(3)
        col5.metric("With Combo Therapy Suggestions", f"{n_combo} ({n_combo/n:.0%})")
        if "tme_phenotype" in df_sum.columns:
            n_inflamed = (df_sum["tme_phenotype"] == "Inflamed").sum()
            n_excluded = (df_sum["tme_phenotype"] == "Excluded").sum()
            col6.metric("Inflamed TME", f"{n_inflamed} ({n_inflamed/n:.0%})")
            col7.metric("Excluded TME", f"{n_excluded} ({n_excluded/n:.0%})")

        st.divider()

        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        fig_c1, fig_c2 = st.columns(2)

        # Immune Activity Score distribution
        with fig_c1:
            if "io_score" in df_sum.columns:
                st.markdown("**Immune Activity Score Distribution**")
                fig, ax = plt.subplots(figsize=(5, 3))
                ax.hist(df_sum["io_score"].dropna(), bins=25, color="#1a9850",
                        alpha=0.8, edgecolor="white")
                ax.axvline(x=50, color="#d73027", linestyle="--", linewidth=1.2,
                           label="Score = 50")
                ax.set_xlabel("Immune Activity Score (0–100)", fontsize=9)
                ax.set_ylabel("Patients", fontsize=9)
                ax.legend(fontsize=8)
                fig.tight_layout()
                st.pyplot(fig, use_container_width=True)
                plt.close()

        # Top targeted drugs bar chart
        with fig_c2:
            if "top_targeted_drug" in df_sum.columns:
                st.markdown("**Top Targeted Drug Distribution**")
                drug_counts = df_sum["top_targeted_drug"].value_counts()
                drug_counts = drug_counts[drug_counts.index.isin(["None", "nan", ""]) == False].head(10)
                if not drug_counts.empty:
                    fig2, ax2 = plt.subplots(figsize=(5, 3))
                    colors = plt.cm.Set2.colors[:len(drug_counts)]
                    ax2.barh(drug_counts.index[::-1], drug_counts.values[::-1],
                             color=list(colors)[::-1], edgecolor="white")
                    ax2.set_xlabel("Patients", fontsize=9)
                    ax2.tick_params(axis="y", labelsize=8)
                    fig2.tight_layout()
                    st.pyplot(fig2, use_container_width=True)
                    plt.close()

        st.divider()

        # Full cohort table
        with st.expander("Full Cohort Summary Table"):
            st.dataframe(df_sum, use_container_width=True, hide_index=True)

    else:
        st.info(
            "Integration summary not yet generated.\n\n"
            "**Step 1:** Run M02 variant annotation:\n"
            "```bash\npython modules/02_variants/luad_pcgr.py\n```\n\n"
            "**Step 2:** Run M07, M08, M03 (optional, for richer scoring):\n"
            "```bash\npython modules/07_drug_mapping/luad_drug_mapping.py\n"
            "python modules/05_pathology/luad_pathology.py\n"
            "python modules/03_expression/luad_expression.py\n```\n\n"
            "**Step 3:** Run M09 integration:\n"
            "```bash\npython modules/09_integration/luad_integration.py\n```"
        )

    st.divider()

    # ── Per-patient recommendation ────────────────────────────────────────────
    st.subheader("Per-Patient Recommendation")

    integration_dir = OUTPUT / "09_integration"
    _m09_all = patients_for_page("09 · Multimodal Integration")
    available = sorted([
        s for s in _m09_all
        if (integration_dir / s / f"{s}_recommendation.tsv").exists()
    ]) if integration_dir.exists() else []

    if available:
        selected = st.selectbox("Select patient", options=available)

        rec_tsv    = integration_dir / selected / f"{selected}_recommendation.tsv"
        report_png = integration_dir / selected / f"{selected}_integration_report.png"

        if report_png.exists():
            st.image(str(report_png), use_container_width=True)

        if rec_tsv.exists():
            st.subheader("All Ranked Recommendations")
            df_rec = pd.read_csv(rec_tsv, sep="\t")

            ICONS = {
                "Targeted Therapy":   "🔵",
                "Immunotherapy":      "🟢",
                "Combination Therapy":"🟣",
                "Chemotherapy":       "🔴",
            }
            df_display = df_rec.copy()
            df_display["category"] = df_display["category"].apply(
                lambda c: f"{ICONS.get(c, '⚪')} {c}"
            )

            # Score bar as emoji-style text
            def score_bar(s):
                filled = int(round(s / 10))
                return "█" * filled + "░" * (10 - filled) + f"  {s}"
            if "confidence" in df_display.columns:
                df_display["confidence"] = df_display["confidence"].apply(score_bar)

            display_cols = [
                "rank", "category", "drug", "drug_class",
                "oncokb_level", "amp_tier", "escat_tier",
                "evidence", "line", "confidence",
                "data_layers", "rationale", "combination_basis",
            ]
            st.dataframe(
                df_display[[c for c in display_cols if c in df_display.columns]],
                use_container_width=True,
                hide_index=True,
            )

            # Evidence legend
            with st.expander("Evidence Grading Reference"):
                st.markdown("""
| OncoKB Level | AMP/ASCO/CAP Tier | Meaning |
|---|---|---|
| Level 1 | Tier I-A | FDA-approved biomarker + same tumor type |
| Level 2 | Tier I-B | NCCN guideline recommendation |
| Level 3A | Tier II-C | Clinical trial evidence / Investigational |
| Level 3B | Tier II-D | Cross-tumor type extrapolation |
| Level 4 | Tier II-D | Preclinical / biological evidence only |
| ESCAT Tier V | — | Combination therapy (co-targeting rationale) |

**IO Score** (0–100) = TMB (0–40) + TME (0–40) + PD-L1 expression (0–15) + IFN-γ signature (0–15) − IO resistance penalty (−20 if STK11/KEAP1/NFE2L2 co-mutation)
                """)
    else:
        st.caption("No per-patient integration reports found. Run M09 to generate them.")


# ══════════════════════════════════════════════════════════════════════════════
# 08 · Multi-modal Immune Activity Score
# ══════════════════════════════════════════════════════════════════════════════

elif page == "08 · Multi-modal Immune Activity Score":
    st.header("08 · Multi-modal Immune Activity Score")
    st.caption(
        "CoxNet (Elastic Net Cox PH) · RNA-seq + immune signatures (TIS/CYT/IMPRES) + "
        "ssGSEA TME (M04) + TIL density (M05) + driver mutations (M02) · "
        "Train: TCGA-LUAD · External validation: GSE72094"
    )

    import json as _json
    scores_path    = OUTPUT / "08_io_ml" / "io_scores.tsv"
    sel_genes_path = OUTPUT / "08_io_ml" / "selected_genes.tsv"
    _metrics_path  = OUTPUT / "08_io_ml" / "model_metrics.json"

    if scores_path.exists():
        df_io = pd.read_csv(scores_path, sep="\t", index_col=0)
        df_io.index.name = "sample_id"
        n = len(df_io)
        grp_counts = df_io["io_group"].value_counts() if "io_group" in df_io.columns else {}
        _m = _json.loads(_metrics_path.read_text()) if _metrics_path.exists() else {}

        tab1, tab2, tab3 = st.tabs([
            "🔬  Model Training",
            "👥  Cohort Overview",
            "👤  Per-Patient Profile",
        ])

        # ══════════════════════════════════════════════════════════════════════
        with tab1:

            # ── 1a Feature Selection ─────────────────────────────────────────
            st.subheader("Feature Selection")
            n_rna  = _m.get("n_rna_selected", "—")
            n_feat = _m.get("n_features", "—")

            fs_c1, fs_c2 = st.columns(2)
            with fs_c1:
                st.markdown("**Stage 1 — RNA gene selection**")
                st.markdown(
                    f"1. Variance pre-filter → top 5,000 genes\n"
                    f"2. Univariate Cox Wald test\n"
                    f"3. CoxNet (Elastic Net Cox PH, 5-fold CV)\n\n"
                    f"**→ {n_rna} RNA genes selected**"
                )
            with fs_c2:
                st.markdown("**Stage 2 — Multi-modal final model**")
                st.markdown(
                    f"Stage-1 RNA genes + immune signatures\n"
                    f"+ ssGSEA TME + TIL + somatic mutations\n"
                    f"+ TMB + pathologic stage + age\n\n"
                    f"**→ {n_feat} features in final CoxNet**"
                )

            st.markdown("**Input modalities**")
            md1, md2, md3 = st.columns(3)
            md1.info("**🧬 RNA-seq (M03)**\n\nCoxNet-selected genes\n\nTIS · CYT · IMPRES")
            md2.info("**🔬 TME + Pathology (M04/M05)**\n\nCD8 T · Treg · NK · M1/M2 · B cell\n\nTIL density · TIL score")
            md3.info("**🏥 Genomics + Clinical (M02)**\n\nSTK11 · KEAP1 · EGFR · KRAS · TMB\n\nStage (I–IV) · Age")

            if sel_genes_path.exists():
                _sg = pd.read_csv(sel_genes_path, sep="\t")
                with st.expander(f"View all {len(_sg)} selected features (CoxNet non-zero coefficients)"):
                    st.dataframe(_sg, use_container_width=True)

            st.divider()

            # ── 1b Model Performance ─────────────────────────────────────────
            st.subheader("Model Performance")
            ci_str = (f"{_m['bootstrap_cindex']}  "
                      f"(95% CI {_m['bootstrap_ci_lo']}–{_m['bootstrap_ci_hi']})"
                      if _m else "—")
            ext_ci  = _m.get("external_cindex", "—")
            cv_ci   = _m.get("cv_cindex", "—")
            n_train = _m.get("n_training", "—")

            mc1, mc2, mc3, mc4 = st.columns(4)
            mc1.metric("Bootstrap C-index (TCGA)", ci_str,
                       help="Bootstrap resampling n=200; higher = better discrimination")
            mc2.metric("5-fold CV C-index (TCGA)", str(cv_ci),
                       help="Nested cross-validation during hyperparameter search")
            mc3.metric("External C-index (GSE72094)", ext_ci,
                       help="TCGA-trained model applied to independent LUAD microarray cohort")
            mc4.metric("Training samples", f"{n_train} (TCGA-LUAD)",
                       help="Samples with OS data used for model training")

            st.markdown("""
**Algorithm**: CoxNet — Elastic Net regularized Cox Proportional Hazards model (`scikit-survival`)
**Hyperparameter tuning**: 5-fold nested cross-validation over grid:
- α ∈ {0.001, …, 1.0} × 20 log-spaced points
- l₁ ratio ∈ {0.1, 0.5, 0.9}

**Scoring**: Linear predictor (Σ βᵢ · xᵢ) from final CoxNet model, inverted (−log_hazard) and normalized to 0–100. High score = low hazard = high immune activity.
            """)

            col_km, col_stk = st.columns(2)
            with col_km:
                show_image(OUTPUT / "08_io_ml" / "figures" / "km_io_score.png",
                           caption="Kaplan-Meier — Immune Activity Score tertile (TCGA-LUAD, log-rank)")
            with col_stk:
                show_image(OUTPUT / "08_io_ml" / "figures" / "km_stk11_subgroup.png",
                           caption="STK11 × Immune Activity Score subgroup")

            gse_km = OUTPUT / "08_io_ml" / "figures" / "km_gse72094.png"
            if gse_km.exists():
                st.markdown("**External validation — GSE72094 (independent LUAD cohort, n=398)**")
                show_image(gse_km,
                           caption="TCGA-trained model applied to GSE72094 microarray (GPL15048). "
                                   "Kaplan-Meier by Immune Activity Score tertile.")

            st.divider()

            # ── 1c Model Interpretability ────────────────────────────────────
            st.subheader("Model Interpretability")
            fi_img = OUTPUT / "08_io_ml" / "figures" / "feature_importance.png"
            if fi_img.exists():
                show_image(fi_img,
                           caption="CoxNet coefficient magnitudes — "
                                   "red = higher expression → higher hazard (worse prognosis); "
                                   "blue = protective")
            st.markdown("""
**Interpretation**: Each coefficient βᵢ represents the log-hazard change per unit increase in that feature (after standardization). Positive → higher expression = higher risk. Negative → protective.

**Modalities included in model**

| Modality | Features | Module |
|----------|----------|--------|
| RNA-seq (Stage 1) | Variance filter → Cox Wald filter → CoxNet selected genes | M03 |
| Immune signatures | TIS (18-gene), CYT (√GZMA×PRF1), IMPRES (15 gene-pairs) | M03 computed |
| ssGSEA TME | CD8 T cytotoxic, Treg, CD8 exhausted, NK, M1/M2, B cell | M04 |
| Histopathology | TIL density, TIL score | M05 |
| Genomics | STK11, KEAP1, EGFR, KRAS, TP53, SMAD4 mutations · TMB | M02 |
| Clinical | Pathologic stage (I–IV), age at diagnosis | TCGA clinical |
            """)

        # ══════════════════════════════════════════════════════════════════════
        with tab2:
            st.subheader("Cohort Overview — TCGA-LUAD")
            cc1, cc2, cc3, cc4 = st.columns(4)
            cc1.metric("Patients scored", n)
            cc2.metric("High immune activity",  int(grp_counts.get("High", 0)),
                       f"{100*grp_counts.get('High',0)/n:.0f}%")
            cc3.metric("Intermediate",           int(grp_counts.get("Intermediate", 0)),
                       f"{100*grp_counts.get('Intermediate',0)/n:.0f}%")
            cc4.metric("Low immune activity",    int(grp_counts.get("Low", 0)),
                       f"{100*grp_counts.get('Low',0)/n:.0f}%")

            st.divider()

            # Score distribution
            import matplotlib.pyplot as plt
            import matplotlib; matplotlib.use("Agg")
            if "io_score" in df_io.columns:
                fig, ax = plt.subplots(figsize=(8, 3))
                colors_map = df_io["io_group"].map(
                    {"High":"#27ae60","Intermediate":"#f39c12","Low":"#e74c3c"})
                ax.hist(df_io["io_score"].dropna(), bins=40,
                        color="#1565c0", alpha=0.75, edgecolor="white")
                q33 = df_io["io_score"].quantile(0.333)
                q67 = df_io["io_score"].quantile(0.667)
                ax.axvline(q33, color="#e74c3c", lw=1.5, ls="--", label="Low/Int boundary")
                ax.axvline(q67, color="#27ae60", lw=1.5, ls="--", label="Int/High boundary")
                ax.set_xlabel("Immune Activity Score (0–100)")
                ax.set_ylabel("Patients")
                ax.set_title("Score distribution across TCGA-LUAD cohort")
                ax.legend(fontsize=8)
                fig.tight_layout()
                st.pyplot(fig)
                plt.close(fig)

            # TIL density by group
            if "til_density" in df_io.columns and df_io["til_density"].notna().sum() > 10:
                fig, ax = plt.subplots(figsize=(6, 3))
                for grp, col in [("High","#27ae60"),("Intermediate","#f39c12"),("Low","#e74c3c")]:
                    vals = df_io[df_io["io_group"]==grp]["til_density"].dropna()
                    if len(vals): ax.hist(vals, bins=25, alpha=0.6, color=col, label=grp)
                ax.set_xlabel("TIL density (M05)"); ax.set_ylabel("Patients")
                ax.set_title("TIL density by Immune Activity group")
                ax.legend(); fig.tight_layout()
                st.pyplot(fig); plt.close(fig)

        # ══════════════════════════════════════════════════════════════════════
        with tab3:
            st.subheader("Per-Patient Immune Activity Profile")
            _m08_samples = sorted(df_io.index.tolist())
            if _m08_samples:
                sel = st.selectbox("Select patient", _m08_samples, key="m08_sample")
                row = df_io.loc[sel]

                io_score = float(row.get("io_score", 0))
                io_group = str(row.get("io_group", "Unknown"))
                group_info = {
                    "High":         ("#27ae60", "High immune activity — strong IO candidate"),
                    "Intermediate": ("#f39c12", "Intermediate — consider clinical context"),
                    "Low":          ("#e74c3c", "Low immune activity — IO may be less effective"),
                }
                color, desc = group_info.get(io_group, ("#888888", ""))
                st.markdown(
                    f"<div style='background:{color}20;border-left:4px solid {color};"
                    f"padding:12px 18px;border-radius:6px;margin-bottom:12px'>"
                    f"<b style='color:{color};font-size:1.15em'>{io_group} immune activity</b>"
                    f" &nbsp;·&nbsp; Score: <b>{io_score:.1f}</b> / 100"
                    f"<br><span style='color:#555;font-size:0.9em'>{desc}</span></div>",
                    unsafe_allow_html=True,
                )

                # 3-modality summary
                pc1, pc2, pc3 = st.columns(3)
                til = row.get("til_density", None)
                pc1.metric("TIL density (M05 · Pathology)",
                           f"{til:.3f}" if pd.notna(til) else "N/A")

                # Immune signatures
                sig_vals = {k: row.get(k, None)
                            for k in ["sig_tis","sig_cyt","sig_impres"]
                            if k in row.index}
                sig_str = "  ·  ".join(
                    f"{k.replace('sig_','').upper()}: {v:.2f}"
                    for k, v in sig_vals.items() if pd.notna(v)
                ) if sig_vals else "N/A"
                pc2.metric("Immune signatures (M03)", sig_str,
                           help="TIS = Tumor Inflammation Signature; CYT = Cytolytic Activity; IMPRES = checkpoint gene-pair score")

                res_cols_map = {"mut_STK11":"STK11","mut_KEAP1":"KEAP1",
                                "mut_EGFR":"EGFR","mut_KRAS":"KRAS"}
                mutated = [name for col, name in res_cols_map.items()
                           if col in row.index and row[col] == 1]
                pc3.metric("Driver mutations (M02)", ", ".join(mutated) if mutated else "None")

                # Clinical features row
                cl1, cl2, cl3 = st.columns(3)
                stage_val = row.get("clinical_stage", None)
                stage_map_inv = {1:"I", 2:"II", 3:"III", 4:"IV"}
                stage_str = stage_map_inv.get(int(stage_val), "Unknown") if pd.notna(stage_val) else "Unknown"
                cl1.metric("Pathologic Stage", f"Stage {stage_str}")
                age_val = row.get("clinical_age", None)
                cl2.metric("Age at diagnosis", f"{age_val:.0f} yrs" if pd.notna(age_val) else "N/A")
                tmb_val = row.get("tmb", None)
                cl3.metric("TMB (mut/Mb)", f"{tmb_val:.1f}" if pd.notna(tmb_val) else "N/A",
                           help="Tumor Mutational Burden — higher TMB may predict IO response")

                # TME bar chart (M04 ssGSEA)
                tme_present = {c.replace("tme_","").replace("_"," "): row.get(f"tme_{c}", None)
                               for c in ["CD8_T_cytotoxic","NK","Macrophage_M1",
                                         "Macrophage_M2","Treg","B_cell"]}
                tme_vals = {k: v for k, v in tme_present.items() if pd.notna(v)}
                if tme_vals:
                    import matplotlib.pyplot as plt
                    labels = list(tme_vals.keys())
                    vals   = list(tme_vals.values())
                    bar_colors = ["#e74c3c" if "M2" in l or "Treg" in l else "#3498db"
                                  for l in labels]
                    fig, ax = plt.subplots(figsize=(7, 2.5))
                    ax.barh(labels, vals, color=bar_colors, height=0.5)
                    ax.set_xlabel("ssGSEA score")
                    ax.set_title(f"TME immune cell composition (M04) — {sel}", fontsize=10)
                    ax.invert_yaxis()
                    fig.tight_layout()
                    st.pyplot(fig)
                    plt.close(fig)

                if mutated:
                    resistance = [m for m in mutated if m in ("STK11","KEAP1")]
                    if resistance:
                        st.warning(
                            f"IO resistance markers: **{', '.join(resistance)}** — "
                            "associated with poor immunotherapy response in LUAD "
                            "(Skoulidis et al., NEJM 2018)")
                    else:
                        st.info(f"Driver mutations detected: {', '.join(mutated)}")

    else:
        st.info("Immune Activity Scores not yet generated. Run:\n"
                "```\npython modules/08_io_ml/luad_io_ml.py\n```")


# ══════════════════════════════════════════════════════════════════════════════
# 10 · CLINICAL RECOMMENDATION
# ══════════════════════════════════════════════════════════════════════════════

elif page == "10 · Clinical Recommendation":
    st.header("10 · Clinical Recommendation")
    st.caption(
        "Clinical trial matching · MDT report · "
        "21 curated LUAD trials (Phase I–III) · "
        "Matched on mutation / TMB / TME phenotype"
    )

    M10_DIR = OUTPUT / "10_clinical_rec"
    _m10_available = sorted([
        d.name for d in M10_DIR.iterdir()
        if d.is_dir() and d.name.startswith("TCGA")
        and (M10_DIR / d.name / f"{d.name}_mdt_report.png").exists()
    ]) if M10_DIR.exists() else []

    if not _m10_available:
        st.info(
            "M10 reports not yet generated. Run:\n"
            "```bash\npython modules/10_clinical_rec/luad_clinical_rec.py\n```"
        )
    else:
        sel_m10 = st.selectbox("Select patient", _m10_available, key="m10_sel")

        tab_mdt, tab_trials = st.tabs(["📋  MDT Report", "🔬  Clinical Trial Matching"])

        # ── MDT Report ───────────────────────────────────────────────────────
        with tab_mdt:
            mdt_png = M10_DIR / sel_m10 / f"{sel_m10}_mdt_report.png"
            if mdt_png.exists():
                show_image(mdt_png, caption=f"MDT Clinical Report — {sel_m10}")
            else:
                st.warning("MDT report image not found.")

        # ── Clinical Trial Matching ───────────────────────────────────────────
        with tab_trials:
            trial_tsv = M10_DIR / sel_m10 / f"{sel_m10}_matched_trials.tsv"
            if trial_tsv.exists():
                df_trials = pd.read_csv(trial_tsv, sep="\t")

                n_elig = (df_trials["match_level"] == "Eligible").sum()
                n_pot  = (df_trials["match_level"] == "Potentially Eligible").sum()

                tc1, tc2, tc3 = st.columns(3)
                tc1.metric("Eligible trials",            n_elig)
                tc2.metric("Potentially eligible trials", n_pot)
                tc3.metric("Total matched",               n_elig + n_pot)

                st.divider()

                # Color-code by match level
                def _trial_row_style(row):
                    color = "#d4efdf" if row["match_level"] == "Eligible" else "#fdebd0"
                    return [f"background-color: {color}"] * len(row)

                display_cols = [
                    "name", "nct_id", "drug", "target", "phase", "status",
                    "line", "match_level", "match_basis", "key_result", "reference",
                ]
                df_show = df_trials[[c for c in display_cols if c in df_trials.columns]]

                st.dataframe(
                    df_show.style.apply(_trial_row_style, axis=1),
                    use_container_width=True,
                    hide_index=True,
                )

                with st.expander("About the trial database"):
                    st.markdown("""
**21 curated LUAD clinical trials** covering:

| Target | Trials |
|--------|--------|
| KRAS G12C | CodeBreaK 200, KRYSTAL-12, KRYSTAL-7 |
| EGFR | FLAURA2, PAPILLON, MARIPOSA |
| ALK | CROWN, ALEX |
| RET fusion | LIBRETTO-431 |
| MET exon14 | GEOMETRY, VISION |
| ERBB2/HER2 | DESTINY-Lung02 |
| NTRK | LOXO-TRK-14001 |
| BRAF V600E | BRF113928 |
| TMB-high | KEYNOTE-158, CheckMate 227 |
| Inflamed TME | KEYNOTE-010, KEYNOTE-024, SKYSCRAPER-01 |
| No driver | TROPION-Lung08 |
| KRAS+STK11 | CodeBreaK 101 |

**Match criteria**: Eligible = required mutation/TMB/TME present; Potentially Eligible = partial match (e.g., mutation present but TME suboptimal).
                    """)
            else:
                st.info(f"No matched trials found for {sel_m10}.")
