"""
streamlit_app.py
----------------
LUAD Precision Oncology Platform — Interactive Dashboard

Displays pre-computed analysis results from the 7-module pipeline.
Run with:  streamlit run streamlit_app.py
"""

import streamlit as st
import pandas as pd
from pathlib import Path

# ── Page config (must be first Streamlit call) ─────────────────────────────
st.set_page_config(
    page_title="LUAD Precision Oncology Platform",
    page_icon="🫁",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Bottom-left site link ───────────────────────────────────────────────────
st.markdown("""
<style>
.bottom-link {
    position: fixed;
    bottom: 16px;
    left: 24px;
    z-index: 9999;
    background-color: #1565c0;
    border-radius: 8px;
    padding: 8px 16px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.30);
}
.bottom-link a {
    color: #ffffff !important;
    text-decoration: none !important;
    font-size: 0.88rem;
    font-weight: 600;
    letter-spacing: 0.2px;
}
.bottom-link a:hover {
    color: #bbdefb !important;
}
</style>
<div class="bottom-link">
    <a href="https://yujuan-zhang.github.io/" title="Yujuan Zhang, PhD">Yujuan Zhang, PhD</a>
</div>
""", unsafe_allow_html=True)

# ── Paths ──────────────────────────────────────────────────────────────────
# All output files live under data/output/, relative to this script
OUTPUT = Path(__file__).parent / "data" / "output"

# ── Per-module sample discovery ────────────────────────────────────────────
def discover_module_samples(module_out_dir: Path, file_suffix: str) -> list:
    """Return sorted list of patient IDs that have output for a given module."""
    if not module_out_dir.exists():
        return []
    return sorted([
        d.name for d in module_out_dir.iterdir()
        if d.is_dir() and (d / f"{d.name}{file_suffix}").exists()
    ])

def discover_clinical_samples() -> list:
    """Return patient IDs from the clinical TSV (broadest list)."""
    tsv = Path(__file__).parent / "data" / "clinical" / "tcga_luad_clinical.tsv"
    if not tsv.exists():
        return []
    try:
        df = pd.read_csv(tsv, sep="\t", usecols=["sample_id"])
        return sorted(df["sample_id"].dropna().tolist())
    except Exception:
        return []

# Global fallback (used when page doesn't have its own selector)
SAMPLES = discover_module_samples(OUTPUT / "02_variants", "_variants.tsv.gz") \
          or ["TCGA-86-A4D0", "TCGA-49-4507"]

@st.cache_data
def load_cohort_index() -> pd.DataFrame:
    """Load cross-module modality index generated by run_all.py."""
    path = Path(__file__).parent / "data" / "output" / "cohort_index.tsv"
    if path.exists():
        return pd.read_csv(path, sep="\t")
    # Fallback: build from filesystem if file not yet generated
    idx = pd.DataFrame({"sample_id": SAMPLES})
    idx["has_rnaseq"]     = idx["sample_id"].apply(lambda s: (OUTPUT / "03_expression" / s).exists())
    idx["has_wes"]        = idx["sample_id"].apply(lambda s: (OUTPUT / "02_variants" / s).exists())
    idx["has_pathology"]  = idx["sample_id"].apply(lambda s: (OUTPUT / "05_pathology" / s).exists())
    idx["has_proteomics"] = False
    idx["modality_count"] = idx[["has_rnaseq","has_wes","has_pathology","has_proteomics"]].sum(axis=1)
    return idx

def patients_for_page(page: str) -> list:
    """Return the appropriate patient list for each module page."""
    idx = load_cohort_index()
    if page in ("07 · ESM2",):
        return idx[idx.has_wes]["sample_id"].tolist()
    if page in ("09 · Multimodal Integration", "10 · Clinical Recommendation"):
        return idx[idx.has_wes & idx.has_rnaseq]["sample_id"].tolist()
    if page in ("05 · Pathology",):
        return idx[idx.has_pathology]["sample_id"].tolist()
    return idx["sample_id"].tolist()

# ── Helper: safe image display ─────────────────────────────────────────────
def show_image(path: Path, caption: str = "", width: int = None):
    """Display an image if the file exists, otherwise show a warning."""
    if path.exists():
        if width:
            st.image(str(path), caption=caption, width=width)
        else:
            st.image(str(path), caption=caption, use_container_width=True)
    else:
        st.info(f"Output not yet available: `{path.name}`\n\nRun the pipeline to generate this file.")


# ── Helper: safe table display ─────────────────────────────────────────────
def show_table(path: Path, sep: str = "\t", nrows: int = 200, caption: str = ""):
    """Display a TSV/CSV as a Streamlit dataframe, with row limit for large files."""
    if not path.exists():
        st.info(f"Output not yet available: `{path.name}`")
        return
    try:
        df = pd.read_csv(path, sep=sep, nrows=nrows)
        if caption:
            st.caption(caption)
        st.dataframe(df, use_container_width=True)
        if len(df) == nrows:
            st.caption(f"Showing first {nrows} rows. Full file: `{path}`")
    except Exception as e:
        st.error(f"Could not load `{path.name}`: {e}")


# ── Pipeline architecture figure ───────────────────────────────────────────
@st.cache_data
def make_pipeline_figure():
    """Generate the 8-module pipeline architecture diagram. Returns a PNG BytesIO."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        from matplotlib.patches import FancyBboxPatch
    except ImportError:
        return None

    fig, ax = plt.subplots(figsize=(12, 11))
    ax.set_xlim(0, 12)
    ax.set_ylim(0, 12)
    ax.axis("off")
    fig.patch.set_facecolor("#ffffff")

    def fbox(x, y, w, h, bg, bd, lw=1.5):
        ax.add_patch(FancyBboxPatch(
            (x, y), w, h, boxstyle="round,pad=0.12",
            facecolor=bg, edgecolor=bd, linewidth=lw, zorder=3,
        ))

    def txt(x, y, s, size=9, color="#1a1a2e", bold=False, ha="center", va="center"):
        ax.text(x, y, s, fontsize=size, color=color,
                fontweight="bold" if bold else "normal",
                ha=ha, va=va, zorder=4, multialignment="center")

    def arrow_dn(x, y_start, y_end):
        ax.annotate("", xy=(x, y_end), xytext=(x, y_start),
                    arrowprops=dict(arrowstyle="-|>", color="#607d8b",
                                   lw=1.8, mutation_scale=16), zorder=2)

    def arrow_rt(x_start, x_end, y):
        ax.annotate("", xy=(x_end, y), xytext=(x_start, y),
                    arrowprops=dict(arrowstyle="-|>", color="#9c27b0",
                                   lw=1.5, mutation_scale=14), zorder=2)

    # Title
    txt(6.0, 11.55, "Pipeline Architecture", size=13, bold=True, color="#1a1a2e")

    # INPUT — two data sources
    fbox(0.3, 10.05, 11.4, 0.95, "#f5f5f5", "#9e9e9e", lw=1.5)
    txt(6.0, 10.65, "INPUT", size=8.5, bold=True, color="#555")
    txt(6.0, 10.25,
        "MAF (somatic variants)  ·  RNA-seq TPM  ·  GDC clinical  ·  H&E WSI slides",
        size=7.5, color="#777")
    arrow_dn(6.0, 10.05, 9.32)

    # STAGE 1 — M01–M04 molecular + M08 imaging (parallel)
    fbox(0.2, 7.60, 11.6, 1.70, "#e3f2fd", "#1565c0", lw=2)
    txt(0.55, 9.13, "STAGE 1  —  Independent modules (run in parallel)",
        size=8.5, bold=True, color="#1565c0", ha="left")
    bw, bh1 = 2.0, 1.05

    # M01–M04
    for i, (num, name) in enumerate([
        ("01", "Patient\nContext"), ("02", "Variation\nAnnotation"),
        ("03", "Expression\nAnalysis"), ("04", "Single-Cell\nTME"),
    ]):
        xi = 0.4 + i * 2.3
        fbox(xi, 7.75, bw, bh1, "white", "#1565c0", lw=1.5)
        txt(xi + bw / 2, 7.75 + bh1 * 0.70, f"M{num}", size=10, bold=True, color="#1565c0")
        txt(xi + bw / 2, 7.75 + bh1 * 0.28, name, size=7.5, color="#333")

    # M08 — imaging module (purple, same stage)
    fbox(9.6, 7.75, bw, bh1, "#f3e5f5", "#6a1b9a", lw=1.8)
    txt(9.6 + bw / 2, 7.75 + bh1 * 0.70, "M08", size=10, bold=True, color="#6a1b9a")
    txt(9.6 + bw / 2, 7.75 + bh1 * 0.28, "Computational\nPathology", size=7.5, color="#333")

    arrow_dn(5.6, 7.60, 6.87)

    # STAGE 2
    fbox(1.3, 5.20, 8.4, 1.65, "#e8f5e9", "#2e7d32", lw=2)
    txt(1.65, 6.68, "STAGE 2  —  Depends on Stage 1 outputs",
        size=8.5, bold=True, color="#2e7d32", ha="left")
    bh2 = 1.08
    for (num, name), xi in zip(
        [("05", "Pathway\nEnrichment"), ("07", "Drug\nMapping")], [2.5, 5.9]
    ):
        fbox(xi, 5.37, bw, bh2, "white", "#2e7d32", lw=1.5)
        txt(xi + bw / 2, 5.37 + bh2 * 0.70, f"M{num}", size=10, bold=True, color="#2e7d32")
        txt(xi + bw / 2, 5.37 + bh2 * 0.28, name, size=7.5, color="#333")

    # M08 feeds into Stage 2 via arrow
    arrow_rt(10.6, 9.7, 6.28)
    fbox(9.6, 5.37, bw, bh2, "#f3e5f5", "#6a1b9a", lw=1.5)
    txt(9.6 + bw / 2, 5.37 + bh2 * 0.70, "M08", size=10, bold=True, color="#6a1b9a")
    txt(9.6 + bw / 2, 5.37 + bh2 * 0.28, "Pathology\nReport", size=7.5, color="#333")

    arrow_dn(5.6, 5.20, 4.52)

    # STAGE 3
    fbox(2.8, 3.05, 5.4, 1.45, "#fff3e0", "#e65100", lw=2)
    txt(3.10, 4.35, "STAGE 3  —  GPU recommended (optional)",
        size=8.5, bold=True, color="#e65100", ha="left")
    fbox(4.4, 3.20, bw, 0.95, "white", "#e65100", lw=1.5)
    txt(4.4 + bw / 2, 3.20 + 0.95 * 0.70, "M06", size=10, bold=True, color="#e65100")
    txt(4.4 + bw / 2, 3.20 + 0.95 * 0.28, "ESM2\nEmbeddings", size=7.5, color="#333")
    arrow_dn(5.6, 3.05, 2.37)

    # DASHBOARD
    fbox(2.0, 1.40, 8.0, 0.95, "#1565c0", "#0d47a1", lw=2)
    txt(6.0, 1.93, "STREAMLIT DASHBOARD", size=10.5, bold=True, color="white")
    txt(6.0, 1.58, "Interactive multi-omics + pathology results explorer", size=7.5, color="#bbdefb")

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=150, bbox_inches="tight",
                facecolor="white", edgecolor="none")
    buf.seek(0)
    plt.close(fig)
    return buf


# ══════════════════════════════════════════════════════════════════════════════
# SIDEBAR
# ══════════════════════════════════════════════════════════════════════════════

with st.sidebar:
    st.markdown("## 🫁 LUAD Platform")
    st.markdown("**Precision Oncology · Multi-Omics**")
    st.divider()

    # Page selector
    page = st.radio(
        "Navigate",
        options=[
            "Home",
            "01 · Patients",
            "02 · Variants",
            "03 · Expression",
            "04 · Single-Cell TME",
            "05 · Pathology",
            "06 · Pathway",
            "07 · ESM2",
            "08 · IO ML",
            "09 · Multimodal Integration",
            "10 · Clinical Recommendation",
        ],
        label_visibility="collapsed",
    )

    st.divider()
    st.caption("Data: TCGA-LUAD · GSE131907")
    st.caption("Model: ESM2-650M · PCGR v2.2.5")


# ══════════════════════════════════════════════════════════════════════════════
# HOME PAGE
# ══════════════════════════════════════════════════════════════════════════════

if page == "Home":

    # ── Global CSS ──────────────────────────────────────────────────────────
    st.markdown("""
    <style>
    /* Hero banner */
    .hero-banner {
        background: linear-gradient(150deg, #0a1628 0%, #12263f 55%, #0f3460 100%);
        border-radius: 14px;
        padding: 52px 48px 44px 48px;
        margin-bottom: 28px;
        color: white;
        position: relative;
        overflow: hidden;
    }
    .hero-accent {
        position: absolute;
        top: 0; left: 0; right: 0;
        height: 4px;
        background: linear-gradient(90deg, #1976d2, #42a5f5, #64b5f6, #29b6f6);
        border-radius: 14px 14px 0 0;
    }
    .hero-eyebrow {
        font-size: 0.70rem;
        letter-spacing: 2.5px;
        color: #42a5f5;
        text-transform: uppercase;
        font-weight: 700;
        margin-bottom: 14px;
    }
    .hero-title {
        font-size: 2.75rem;
        font-weight: 800;
        margin: 0 0 14px 0;
        letter-spacing: -0.8px;
        line-height: 1.15;
    }
    .hero-subtitle {
        font-size: 0.98rem;
        color: #b0c4de;
        margin: 0 0 28px 0;
        font-weight: 400;
        line-height: 1.65;
        max-width: 680px;
    }
    /* Badge pills — outlined style */
    .badge-row { margin-top: 0; display: flex; flex-wrap: wrap; gap: 8px; }
    .badge {
        display: inline-block;
        padding: 4px 14px;
        border-radius: 20px;
        font-size: 0.74rem;
        font-weight: 600;
        letter-spacing: 0.4px;
        border: 1px solid;
    }
    .badge-blue   { border-color: #42a5f5; color: #90caf9; }
    .badge-green  { border-color: #66bb6a; color: #a5d6a7; }
    .badge-purple { border-color: #ba68c8; color: #ce93d8; }
    .badge-orange { border-color: #ffa726; color: #ffcc80; }
    .badge-teal   { border-color: #26a69a; color: #80cbc4; }
    /* Stat cards */
    .stat-grid {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 16px;
        margin-bottom: 32px;
    }
    .stat-card {
        background: #f8f9fa;
        border: 1px solid #e0e0e0;
        border-left: 5px solid #1565c0;
        border-radius: 10px;
        padding: 20px 18px;
        text-align: center;
    }
    .stat-number { font-size: 2rem; font-weight: 800; color: #1565c0; }
    .stat-label  { font-size: 0.82rem; color: #666; margin-top: 4px; }
    /* Module cards */
    .module-grid {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 14px;
        margin-bottom: 32px;
    }
    .module-card {
        border: 1px solid #e0e0e0;
        border-radius: 10px;
        padding: 16px 18px;
        background: white;
        transition: box-shadow 0.2s;
    }
    .module-card:hover { box-shadow: 0 4px 12px rgba(0,0,0,0.1); }
    .module-id {
        display: inline-block;
        background: #1565c0;
        color: white;
        border-radius: 6px;
        padding: 2px 8px;
        font-size: 0.75rem;
        font-weight: 700;
        margin-right: 8px;
    }
    .module-name { font-weight: 700; font-size: 0.97rem; color: #1a1a2e; }
    .module-desc { font-size: 0.82rem; color: #666; margin-top: 6px; }
    .module-tag  {
        display: inline-block;
        background: #e8f0fe;
        color: #1a73e8;
        border-radius: 4px;
        padding: 1px 7px;
        font-size: 0.7rem;
        margin: 4px 3px 0 0;
    }
    /* Pipeline flow */
    .flow-step {
        display: flex;
        align-items: flex-start;
        gap: 16px;
        margin-bottom: 18px;
    }
    .flow-num {
        min-width: 36px;
        height: 36px;
        background: #1565c0;
        color: white;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        font-weight: 800;
        font-size: 0.9rem;
        flex-shrink: 0;
    }
    .flow-text strong { font-size: 0.95rem; color: #1a1a2e; }
    .flow-text p { font-size: 0.83rem; color: #666; margin: 2px 0 0 0; }
    /* Section headings */
    .section-heading {
        font-size: 1.2rem;
        font-weight: 700;
        color: #1a1a2e;
        border-bottom: 2px solid #1565c0;
        padding-bottom: 6px;
        margin: 28px 0 18px 0;
    }
    /* Overview cards */
    .overview-section {
        display: grid;
        grid-template-columns: 1fr 1fr 1fr;
        gap: 20px;
        margin-bottom: 32px;
    }
    .overview-card {
        border-radius: 12px;
        padding: 22px 20px;
    }
    .overview-card h4 {
        font-size: 0.95rem;
        font-weight: 700;
        margin: 0 0 12px 0;
    }
    .overview-card ul {
        margin: 0;
        padding-left: 18px;
    }
    .overview-card li {
        font-size: 0.83rem;
        line-height: 1.7;
        margin-bottom: 4px;
    }
    .ov-bg1 { background: #e8f0fe; border-left: 4px solid #1565c0; }
    .ov-bg1 h4 { color: #1565c0; }
    .ov-bg2 { background: #fce8e6; border-left: 4px solid #c62828; }
    .ov-bg2 h4 { color: #c62828; }
    .ov-bg3 { background: #e6f4ea; border-left: 4px solid #2e7d32; }
    .ov-bg3 h4 { color: #2e7d32; }
    </style>
    """, unsafe_allow_html=True)

    # ── Hero Banner ──────────────────────────────────────────────────────────
    st.markdown("""
    <div class="hero-banner">
        <div class="hero-accent"></div>
        <div class="hero-eyebrow">Precision Oncology &nbsp;·&nbsp; Multi-Omics &nbsp;·&nbsp; TCGA-LUAD</div>
        <div class="hero-title">LUAD Precision Oncology Platform</div>
        <div class="hero-subtitle">
            A 7-module multi-omics pipeline integrating somatic variant annotation,
            tumor microenvironment profiling, ESM2 protein language model embeddings,
            and evidence-based drug mapping for lung adenocarcinoma precision medicine.
        </div>
        <div class="badge-row">
            <span class="badge badge-blue">Python 3.10+</span>
            <span class="badge badge-green">ESM2-650M</span>
            <span class="badge badge-purple">PCGR v2.2.5</span>
            <span class="badge badge-orange">TCGA-LUAD</span>
            <span class="badge badge-teal">CIViC · NCCN/FDA</span>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Overview (plain markdown, no HTML cards) ─────────────────────────────
    st.markdown("---")
    st.markdown("""
### Overview

Lung adenocarcinoma (LUAD) is the most common subtype of non-small cell lung cancer (NSCLC),
accounting for approximately 40% of all lung cancer diagnoses worldwide and remaining one of
the leading causes of cancer-related mortality globally. Unlike many other cancer types that
respond to a single standard-of-care protocol, LUAD is driven by highly heterogeneous somatic
mutations — a patient harboring an *EGFR* exon 19 deletion responds dramatically to osimertinib,
while a patient with *STK11* loss may derive little benefit from PD-1 checkpoint immunotherapy
even when tumor mutational burden appears high. Identifying the precise molecular profile of
each patient is therefore not optional: it is the foundation of effective treatment selection.

**What does this platform do?**

This platform automatically processes each patient's somatic variant calls, bulk RNA-seq
expression data, and clinical metadata through 7 integrated analysis modules — producing a
structured precision medicine report that addresses four core clinical questions: who is this
patient (survival context, stage, demographics), what mutations does their tumor carry (somatic
variants, TMB, mutational signatures), how is their tumor behaving (gene expression outliers,
immune microenvironment composition, dysregulated pathways), and which treatments have evidence
of efficacy for their specific mutation profile (targeted therapy, immunotherapy, chemotherapy).

**Why was this platform built — pain points addressed**

Current clinical bioinformatics workflows are fragmented. A typical analysis requires running
Ensembl VEP for variant annotation, a separate script to compute TMB, a dedicated pathway tool
for enrichment analysis, and a manual review of NCCN guidelines and the CIViC database for drug
matching — often across five or more disconnected tools with no shared data schema. Integrating
results across these tools requires significant manual effort, is error-prone, and is not
reproducible without careful bookkeeping. This platform replaces the entire toolchain with a
single orchestration command (`python run_all.py`), with automatic inter-module dependency
handling and a unified output structure.

Beyond workflow integration, standard clinical pipelines classify mutations using rule-based
databases (e.g., ClinVar, OncoKB) that assign a pathogenicity label but cannot capture *how
structurally damaging* a mutation is at the protein level. This platform introduces an AI layer
using **ESM2-650M** (Meta AI's protein language model), which extracts 1280-dimensional
embeddings at each missense mutation site and computes masked-marginal log-odds scores —
quantifying the degree to which the mutation is unexpected given the evolutionary context of
the protein. These features enable downstream machine learning–based variant effect prediction
that goes beyond binary rule-based classification.

**Key technical innovations**

*End-to-end automation.* A single command orchestrates all 7 modules in dependency order, with
automatic failure handling. Module 02 (variant annotation) feeds into Module 05 (pathway
enrichment) and Module 07 (drug mapping); if an upstream module fails, dependent modules are
automatically skipped with a clear error message.

*ESM2 protein language model embeddings (Module 06).* For every missense mutation identified
in Module 02, the platform retrieves the canonical protein sequence from UniProt, runs
ESM2-650M inference, and extracts the per-site 1280-dimensional hidden state for both the
wild-type and mutant amino acid. The delta embedding (mutant minus wild-type) serves as a
structural perturbation proxy. These features can be directly fed into supervised classifiers
for pathogenicity prediction or used for unsupervised clustering of mutation types.

*GPT-4o + PubMed literature integration (Module 07).* For each actionable variant identified
in drug mapping, the platform automatically queries PubMed via the NCBI Entrez API for the
most relevant clinical literature, retrieves abstracts from the top papers, and uses GPT-4o
to generate a concise structured clinical summary — covering the mutation's known oncogenic
role, associated therapies, and clinical evidence level. This connects the analysis directly
to the latest published evidence without requiring manual literature review.

*Single-cell tumor microenvironment characterization (Module 04).* The platform integrates
the 57,000-cell Lung Cancer Cell Atlas (GSE131907) to quantify the composition of the tumor
immune microenvironment — including T cell, NK cell, macrophage, dendritic cell, and cancer
cell populations. Immune infiltration patterns are a critical determinant of immunotherapy
response and are rarely assessed in standard clinical bioinformatics pipelines.

*Clinically actionable drug report (Module 07).* All mutation findings are mapped to an
embedded NCCN/FDA-curated knowledge base covering 16 LUAD driver genes, supplemented by
live CIViC REST API queries for additional evidence. Immunotherapy eligibility is assessed
based on TMB threshold (≥10 mut/Mb) and STK11/KEAP1 resistance markers, producing a
report that directly answers which therapy regimen is supported by clinical evidence for
that patient.
    """)
    st.markdown("---")

    # ── Key Stats ────────────────────────────────────────────────────────────
    st.markdown("""
    <div class="stat-grid">
        <div class="stat-card" style="border-left-color:#1565c0;">
            <div class="stat-number">8</div>
            <div class="stat-label">Analysis Modules</div>
        </div>
        <div class="stat-card" style="border-left-color:#2e7d32;">
            <div class="stat-number">5</div>
            <div class="stat-label">TCGA-LUAD Samples</div>
        </div>
        <div class="stat-card" style="border-left-color:#6a1b9a;">
            <div class="stat-number">1280</div>
            <div class="stat-label">ESM2 Embedding Dims</div>
        </div>
        <div class="stat-card" style="border-left-color:#e65100;">
            <div class="stat-number">~20K</div>
            <div class="stat-label">Genes Covered (RNA-seq)</div>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Module Cards ─────────────────────────────────────────────────────────
    st.markdown('<div class="section-heading">Analysis Modules</div>', unsafe_allow_html=True)
    st.markdown("""
    <div class="module-grid">
        <div class="module-card">
            <span class="module-id">01</span>
            <span class="module-name">Patients</span>
            <div class="module-desc">GDC clinical data retrieval · Kaplan-Meier survival curves · patient summary card</div>
            <span class="module-tag">Clinical</span>
            <span class="module-tag">Survival</span>
        </div>
        <div class="module-card">
            <span class="module-id">02</span>
            <span class="module-name">Variants</span>
            <div class="module-desc">VEP/PCGR somatic annotation · tumor mutational burden (TMB) · SBS mutational spectrum</div>
            <span class="module-tag">Genomics</span>
            <span class="module-tag">TMB</span>
            <span class="module-tag">VEP</span>
        </div>
        <div class="module-card">
            <span class="module-id">03</span>
            <span class="module-name">Expression</span>
            <div class="module-desc">Bulk RNA-seq TPM normalization · cohort-level outlier gene detection · clinical gene panel</div>
            <span class="module-tag">RNA-seq</span>
            <span class="module-tag">Outlier</span>
        </div>
        <div class="module-card">
            <span class="module-id">04</span>
            <span class="module-name">Single-cell TME</span>
            <div class="module-desc">ssGSEA cell-type deconvolution · GSE131907 reference · immune phenotype (Inflamed / Excluded / Desert)</div>
            <span class="module-tag">scRNA</span>
            <span class="module-tag">Immune</span>
            <span class="module-tag">TME</span>
        </div>
        <div class="module-card">
            <span class="module-id" style="background:#6a1b9a;">05</span>
            <span class="module-name">Pathology</span>
            <div class="module-desc">H&E slide analysis · tissue segmentation · TIL density scoring · TME phenotype classification</div>
            <span class="module-tag" style="background:#f3e5f5;color:#6a1b9a;">Pathology</span>
            <span class="module-tag">H&amp;E</span>
            <span class="module-tag">TIL</span>
            <span class="module-tag">WSI</span>
        </div>
        <div class="module-card">
            <span class="module-id">06</span>
            <span class="module-name">Pathway</span>
            <div class="module-desc">Over-representation analysis (ORA) on mutated genes · GSEA prerank on expression fold-changes</div>
            <span class="module-tag">ORA</span>
            <span class="module-tag">GSEA</span>
        </div>
        <div class="module-card">
            <span class="module-id" style="background:#e65100;">07</span>
            <span class="module-name">ESM2</span>
            <div class="module-desc">Per-site 1280-dim protein embeddings · masked-marginal log-odds · variant effect prediction <em>(GPU recommended)</em></div>
            <span class="module-tag" style="background:#fff3e0;color:#e65100;">GPU</span>
            <span class="module-tag">ESM2</span>
            <span class="module-tag">Embeddings</span>
        </div>
        <div class="module-card">
            <span class="module-id" style="background:#1565c0;">08</span>
            <span class="module-name">IO ML</span>
            <div class="module-desc">TIS · CYT · TIDE · IMPRES algorithms · composite IO response score · IO resistance detection</div>
            <span class="module-tag" style="background:#e3f2fd;color:#1565c0;">ML</span>
            <span class="module-tag">Immunotherapy</span>
            <span class="module-tag">Prediction</span>
        </div>
        <div class="module-card">
            <span class="module-id" style="background:#2e7d32;">09</span>
            <span class="module-name">Multimodal Integration</span>
            <div class="module-desc">Multi-omics evidence integration · M02+M03+M04+M05+M08 · treatment confidence scoring</div>
            <span class="module-tag" style="background:#e8f5e9;color:#2e7d32;">Integration</span>
            <span class="module-tag">Multi-omics</span>
        </div>
        <div class="module-card">
            <span class="module-id" style="background:#b71c1c;">10</span>
            <span class="module-name">Clinical Recommendation</span>
            <div class="module-desc">OncoKB · AMP/ASCO/CAP · ESCAT evidence grading · ranked targeted / IO / combination therapy</div>
            <span class="module-tag" style="background:#ffebee;color:#b71c1c;">Clinical</span>
            <span class="module-tag">NCCN</span>
            <span class="module-tag">CIViC</span>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Sample Coverage Table ────────────────────────────────────────────────
    st.markdown('<div class="section-heading">Demo Samples</div>', unsafe_allow_html=True)
    _demo_ids = (SAMPLES[:5] if len(SAMPLES) >= 5
                 else SAMPLES + ["—"] * (5 - len(SAMPLES)))
    demo_data = {
        "Sample ID":  _demo_ids,
        "Variants":   ["✅", "✅", "—", "✅", "—"],
        "RNA-seq":    ["✅", "—", "✅", "—", "✅"],
        "Pathway":    ["✅", "✅", "✅", "✅", "✅"],
        "Drug Report":["✅", "✅", "—", "✅", "—"],
        "ESM2":       ["⏳ GPU", "—", "—", "—", "—"],
        "Pathology":  ["—", "—", "—", "—", "✅"],
    }
    st.dataframe(pd.DataFrame(demo_data), use_container_width=True, hide_index=True)

    # ── Quick Start ──────────────────────────────────────────────────────────
    st.markdown('<div class="section-heading">Quick Start</div>', unsafe_allow_html=True)
    st.code("""# Run full pipeline (all samples, skip ESM2)
python run_all.py

# Run a single sample
python run_all.py --sample TCGA-86-A4D0

# Include ESM2 inference (requires GPU)
python run_all.py --include_esm2

# Validate inputs without running analysis
python run_all.py --dry_run
""", language="bash")

    # ── Footer ───────────────────────────────────────────────────────────────
    st.divider()
    st.markdown("""
    <div style="text-align:center; color:#666; font-size:0.85rem; padding: 8px 0 16px 0;">
        Any questions please contact <strong>Yujuan Zhang, PhD</strong>
        &nbsp;·&nbsp;
        <a href="mailto:yujuan.zhang418@gmail.com" style="color:#1565c0; text-decoration:none;">
            yujuan.zhang418@gmail.com
        </a>
    </div>
    """, unsafe_allow_html=True)


# ══════════════════════════════════════════════════════════════════════════════
# 01 · PATIENT CONTEXT
# ══════════════════════════════════════════════════════════════════════════════

elif page == "01 · Patients":
    st.header("01 · Patients")
    st.caption("GDC clinical data · survival analysis · patient summary card")

    # M01 saves cards flat: 01_patients/{id}_patient_card.png (no subdirs)
    _m01_dir = OUTPUT / "01_patients"
    _m01_samples = sorted([
        f.stem.replace("_patient_card", "")
        for f in _m01_dir.glob("*_patient_card.png")
    ]) if _m01_dir.exists() else []
    if not _m01_samples:
        _m01_samples = discover_clinical_samples() or SAMPLES
    sample = st.selectbox("Patient", _m01_samples, key="sel_m01",
                          help=f"{len(_m01_samples)} patients available")

    # Patient card image
    img = OUTPUT / "01_patients" / f"{sample}_patient_card.png"
    show_image(img, caption=f"Patient summary card — {sample}")

    st.divider()

    # Clinical summary table (all samples)
    st.subheader("Cohort Clinical Summary")
    show_table(
        OUTPUT / "01_patients" / "clinical_summary.tsv",
        caption="All available samples · GDC clinical metadata",
    )


# ══════════════════════════════════════════════════════════════════════════════
# 02 · VARIATION ANNOTATION
# ══════════════════════════════════════════════════════════════════════════════

elif page == "02 · Variants":
    st.header("02 · Variants")
    st.caption("Somatic variants annotated with VEP/PCGR · tumor mutational burden · SBS spectrum")

    _m02_samples = discover_module_samples(OUTPUT / "02_variants", "_variants.tsv.gz")
    sample = st.selectbox("Patient", _m02_samples or SAMPLES, key="sel_m02",
                          help=f"{len(_m02_samples)} patients with variant output")

    # Variant summary image
    img = OUTPUT / "02_variants" / sample / f"{sample}_variant_summary.png"
    show_image(img, caption=f"Variant summary — {sample}")

    st.divider()

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Tumor Mutational Burden")
        show_table(
            OUTPUT / "02_variants" / sample / f"{sample}_tmb.tsv",
            caption="TMB metrics for this sample",
        )

    with col2:
        st.subheader("Cohort Summary")
        show_table(
            OUTPUT / "02_variants" / "all_samples_summary.tsv",
            caption="Cross-sample variant statistics",
        )

    st.divider()

    st.subheader("Somatic Variants")
    show_table(
        OUTPUT / "02_variants" / sample / f"{sample}_variants.tsv.gz",
        nrows=100,
        caption=f"Top 100 variants shown · {sample}",
    )


# ══════════════════════════════════════════════════════════════════════════════
# 03 · EXPRESSION ANALYSIS
# ══════════════════════════════════════════════════════════════════════════════

elif page == "03 · Expression":
    st.header("03 · Expression")
    st.caption("Bulk RNA-seq · GTEx normal lung baseline · per-patient & cohort-level figures")

    _m03_samples = discover_module_samples(OUTPUT / "03_expression", "_clinical_genes.png")
    sample = st.selectbox("Patient", _m03_samples or SAMPLES, key="sel_m03",
                          help=f"{len(_m03_samples)} patients with expression output")

    # ── Per-patient figures ───────────────────────────────────────────────────
    tab1, tab2, tab3 = st.tabs([
        "📊 Expression Summary",
        "🧬 Clinical Gene Panel",
        "🔬 Mutation–Expression",
    ])

    with tab1:
        show_image(
            OUTPUT / "03_expression" / sample / f"{sample}_expression_summary.png",
            caption=f"Expression outliers vs GTEx Normal Lung — {sample}",
        )
        st.divider()
        st.subheader("Expression Outlier Genes")
        st.caption("Genes with |GTEx Z-score| > 2 (tumor vs normal lung). First 200 rows.")
        outliers_tsv = OUTPUT / "03_expression" / sample / f"{sample}_expression_outliers.tsv.gz"
        if not outliers_tsv.exists():
            outliers_tsv = OUTPUT / "03_expression" / sample / f"{sample}_expression_outliers.tsv"
        if outliers_tsv.exists():
            show_table(outliers_tsv, nrows=200, caption=f"Outlier genes — {sample}")
        else:
            st.info("Detailed outlier table available in local pipeline output only.")
        st.divider()
        st.subheader("Cohort-level Overview")
        col1, col2 = st.columns(2)
        with col1:
            show_image(
                OUTPUT / "03_expression" / "cohort_clinical_genes_heatmap.png",
                caption="Clinical gene Z-scores — 517 patients × 21 genes",
            )
        with col2:
            show_image(
                OUTPUT / "03_expression" / "cohort_outlier_distribution.png",
                caption="Outlier gene counts per patient vs GTEx Normal Lung",
            )

    with tab2:
        show_image(
            OUTPUT / "03_expression" / sample / f"{sample}_clinical_genes.png",
            caption=f"LUAD clinical gene expression vs GTEx Normal Lung — {sample}",
        )

    with tab3:
        mut_img = OUTPUT / "03_expression" / sample / f"{sample}_mutation_expression.png"
        if mut_img.exists():
            show_image(mut_img,
                       caption=f"Mutated gene expression positions — {sample}")
        else:
            st.info("No mutation data available for this patient (M02 output not found).")


# ══════════════════════════════════════════════════════════════════════════════
# 04 · SINGLE-CELL TME  (sample-independent)
# ══════════════════════════════════════════════════════════════════════════════

elif page == "04 · Single-Cell TME":
    st.header("04 · Single-Cell Tumor Microenvironment")
    st.caption("Stage 1: GSE131907 single-cell reference · Stage 2: ssGSEA deconvolution of TCGA bulk RNA-seq")

    tab1, tab2 = st.tabs(["Cohort TME (ssGSEA)", "Single-Cell Reference (GSE131907)"])

    # ── Tab 1: ssGSEA cohort deconvolution ──────────────────────────────────────
    with tab1:
        st.subheader("TCGA-LUAD Immune Phenotype Distribution")

        cohort_scores_path = OUTPUT / "04_single_cell" / "tme_cohort_scores.tsv"
        if cohort_scores_path.exists():
            df_tme = pd.read_csv(cohort_scores_path, sep="\t")

            # Phenotype summary metrics
            if "immune_phenotype" in df_tme.columns:
                n_total = len(df_tme)
                pc = df_tme["immune_phenotype"].value_counts()
                c1, c2, c3 = st.columns(3)
                colors_map = {"Inflamed": "🟢", "Excluded": "🟡", "Desert": "🔴"}
                for col, ptype in zip([c1, c2, c3], ["Inflamed", "Excluded", "Desert"]):
                    n = pc.get(ptype, 0)
                    col.metric(
                        f"{colors_map.get(ptype,'⚪')} {ptype}",
                        f"{n}",
                        f"{100*n/n_total:.0f}% of cohort",
                    )

            st.divider()

            # Cohort heatmap
            show_image(
                OUTPUT / "04_single_cell" / "tme_cohort_heatmap.png",
                caption="Cohort TME heatmap — ssGSEA enrichment scores × 517 TCGA-LUAD patients",
            )

            st.divider()

            # Per-patient selector
            st.subheader("Per-Patient TME Profile")
            _m04_samples = patients_for_page("04 · Single-Cell TME")
            if _m04_samples:
                sel_sample = st.selectbox(
                    "Select patient", _m04_samples,
                    key="m04_sample",
                    index=_m04_samples.index("TCGA-86-A4D0") if "TCGA-86-A4D0" in _m04_samples else 0,
                )
                tme_path = OUTPUT / "04_single_cell" / sel_sample / f"{sel_sample}_tme_scores.tsv"
                if tme_path.exists():
                    df_pat = pd.read_csv(tme_path, sep="\t")
                    cell_cols = [c for c in df_pat.columns if c not in ("sample_id", "immune_phenotype")]
                    phenotype = df_pat["immune_phenotype"].iloc[0] if "immune_phenotype" in df_pat.columns else "Unknown"

                    # Phenotype badge
                    ph_info = {
                        "Inflamed": ("🟢", "High immune infiltration — potential IO responder"),
                        "Excluded": ("🟡", "Immune cells confined to stroma — partial IO resistance"),
                        "Desert":   ("🔴", "Low immune infiltration — IO likely ineffective"),
                    }
                    icon, desc = ph_info.get(phenotype, ("⚪", ""))
                    st.info(f"**{icon} TME Phenotype: {phenotype}** — {desc}")

                    # Bar chart of ssGSEA scores
                    import matplotlib.pyplot as plt
                    scores_row = df_pat[cell_cols].iloc[0]
                    fig_bar, ax_bar = plt.subplots(figsize=(9, 3.5))
                    bars = ax_bar.bar(cell_cols, scores_row.values, color="#4e79a7", edgecolor="white")
                    ax_bar.set_ylabel("ssGSEA Enrichment Score")
                    ax_bar.set_title(f"TME Cell-Type Profile — {sel_sample}")
                    ax_bar.set_xticklabels(cell_cols, rotation=35, ha="right", fontsize=9)
                    fig_bar.tight_layout()
                    st.pyplot(fig_bar)
                    plt.close(fig_bar)
                else:
                    st.info("Per-patient TME file not found. Run module 04 locally.")

            st.divider()

            # Full cohort table
            with st.expander("Full Cohort ssGSEA Scores Table"):
                show_table(cohort_scores_path, nrows=520, caption="ssGSEA scores — all 517 TCGA-LUAD patients")
        else:
            st.info("Cohort TME scores not yet generated. Run: `python modules/04_single_cell/luad_singlecell.py --skip_sc`")

    # ── Tab 2: GSE131907 single-cell reference ───────────────────────────────────
    with tab2:
        st.subheader("GSE131907 Single-Cell Reference (Kim et al. 2020)")
        st.caption("58 tLung samples · cell-type fractions · immune phenotype classification")

        show_image(
            OUTPUT / "04_single_cell" / "luad_tme_overview.png",
            caption="GSE131907 Lung Cancer Cell Atlas — TME overview",
        )

        st.divider()

        col1, col2 = st.columns(2)
        with col1:
            st.subheader("Per-Sample Immune Metrics")
            show_table(
                OUTPUT / "04_single_cell" / "per_sample_immune_metrics.tsv",
                caption="Immune score, stromal score, estimate score",
            )
        with col2:
            st.subheader("Cell-Type Fractions")
            show_table(
                OUTPUT / "04_single_cell" / "per_sample_tme_fractions.tsv",
                caption="Relative abundance of each TME cell type",
            )

        st.divider()
        st.subheader("TME Summary")
        show_table(
            OUTPUT / "04_single_cell" / "luad_tme_summary.tsv",
            caption="Cohort-level TME summary statistics",
        )


# ══════════════════════════════════════════════════════════════════════════════
# 05 · PATHWAY ENRICHMENT
# ══════════════════════════════════════════════════════════════════════════════

elif page == "06 · Pathway":
    st.header("06 · Pathway")
    st.caption("KEGG pathway viewer · ORA on mutated genes · GSEA prerank on expression")

    _m05_gsea = discover_module_samples(OUTPUT / "06_pathway", "_gsea.tsv")
    _m05_ora  = discover_module_samples(OUTPUT / "06_pathway", "_ora.tsv")
    _m05_samples = sorted(set(_m05_gsea) | set(_m05_ora))
    sample = st.selectbox("Patient", _m05_samples or SAMPLES, key="sel_m05",
                          help=f"{len(_m05_samples)} patients with pathway output ({len(_m05_gsea)} with GSEA)")

    # ── KEGG Pathway Viewer ────────────────────────────────────────────────────
    st.subheader("KEGG Pathway View")
    st.caption("🔴 Mutated · 🟠 High expression (z > 1.5) · 🔵 Low expression (z < −1.5)")

    import sys
    sys.path.insert(0, str(Path(__file__).parent / "modules" / "06_pathway"))
    from kegg_viewer import (
        LUAD_PATHWAYS, load_all_pathway_genes, get_hit_pathways,
        load_mutations, load_expression_colors, build_kegg_url,
        build_gene_table, render_pathway,
    )

    @st.cache_data(show_spinner="Loading KEGG gene sets…", ttl=86400)
    def _load_pathway_genes():
        return load_all_pathway_genes()

    pathway_genes = _load_pathway_genes()
    mutations     = load_mutations(sample)

    if not mutations:
        st.info(f"No variant data found for {sample}. KEGG viewer requires M02 output.")
    else:
        hit_pathways = get_hit_pathways(mutations, pathway_genes)

        # ── Overview bar chart ─────────────────────────────────────────────────
        import matplotlib.pyplot as plt
        all_names = list(LUAD_PATHWAYS.keys())
        hit_dict  = {name: len(hits) for name, _, hits in hit_pathways}

        fig, ax = plt.subplots(figsize=(8, 3.5))
        bar_colors = ["#d62728" if hit_dict.get(n, 0) > 0 else "#cccccc"
                      for n in all_names]
        bars = ax.bar(all_names, [hit_dict.get(n, 0) for n in all_names],
                      color=bar_colors, edgecolor="white", width=0.6)
        ax.set_ylabel("Mutated genes in pathway", fontsize=9)
        ax.set_title(f"LUAD Pathway Hit Summary — {sample}", fontsize=10, fontweight="bold")
        ax.set_xticks(range(len(all_names)))
        ax.set_xticklabels(all_names, rotation=30, ha="right", fontsize=8)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        for bar, n in zip(bars, all_names):
            v = hit_dict.get(n, 0)
            if v > 0:
                ax.text(bar.get_x() + bar.get_width() / 2, v + 0.05,
                        str(v), ha="center", va="bottom", fontsize=9, fontweight="bold")
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

        if not hit_pathways:
            st.info("No mutations fall within the 8 core LUAD pathways for this patient.")

        # ── Manual pathway selector ────────────────────────────────────────────
        hit_names   = [h[0] for h in hit_pathways]
        other_names = [n for n in all_names if n not in hit_names]
        extra = st.multiselect(
            "Add more pathways to view",
            options=other_names, default=[], key="kegg_extra",
        )

        display_pathways = hit_pathways.copy()
        for name in extra:
            pid = LUAD_PATHWAYS[name][0]
            display_pathways.append((name, pid, []))

        # ── Per-pathway detail ─────────────────────────────────────────────────
        for name, pid, hit_genes in display_pathways:
            pg         = pathway_genes.get(pid, [])
            high, low  = load_expression_colors(sample, pg)
            kegg_url   = build_kegg_url(pid, mutations, high, low)
            gene_table = build_gene_table(sample, pg, mutations, high, low)

            n_mut  = len(hit_genes)
            n_high = len([g for g in high if g not in {x.upper() for x in hit_genes}])
            n_low  = len([g for g in low  if g not in {x.upper() for x in hit_genes}])
            label  = (f"🔴 **{name}** — {n_mut} mutated"
                      + (f", {n_high} ↑" if n_high else "")
                      + (f", {n_low} ↓"  if n_low  else ""))

            with st.expander(label, expanded=bool(hit_genes)):
                png_bytes = render_pathway(pid, mutations, high, low)
                if png_bytes:
                    st.image(png_bytes, use_container_width=True)
                else:
                    st.link_button(
                        f"Open {name} in KEGG ↗", url=kegg_url,
                        help="Local image not available — opens KEGG website",
                    )
                if not gene_table.empty:
                    st.markdown("**Genes hit in this patient:**")
                    st.dataframe(gene_table, use_container_width=True, hide_index=True)
                elif hit_genes:
                    st.markdown(f"Mutated: `{'`, `'.join(hit_genes)}`")

    st.divider()

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("GSEA Results")
        show_table(
            OUTPUT / "06_pathway" / sample / f"{sample}_gsea.tsv",
            caption=f"Top enriched gene sets (GSEA prerank) — {sample}",
        )

    with col2:
        st.subheader("ORA Results")
        show_table(
            OUTPUT / "06_pathway" / sample / f"{sample}_ora.tsv",
            caption=f"Over-represented pathways (ORA) — {sample}",
        )

    st.divider()

    # ── Cross-sample pathway frequency ────────────────────────────────────────
    st.subheader("Cross-Sample Pathway Summary")
    st.caption("Pathways ranked by how many patients show significant activation (GSEA FDR < 0.25, NES > 0). "
               "Housekeeping pathways activated in >90% of patients are excluded.")

    summary_path = OUTPUT / "06_pathway" / "all_samples_summary.tsv"
    if summary_path.exists():
        import matplotlib.pyplot as plt

        pw_df = pd.read_csv(summary_path, sep="\t")

        luad_only = st.checkbox("Show LUAD-relevant pathways only", value=False)
        if luad_only:
            pw_df = pw_df[pw_df["luad_relevant"] == True]

        top_n = st.slider("Number of pathways to display", 10, 50, 20)
        plot_df = pw_df.head(top_n).sort_values("pct_patients")

        fig, ax = plt.subplots(figsize=(9, max(4, len(plot_df) * 0.38)))
        colors = ["#2ca02c" if r else "#4393c3"
                  for r in plot_df["luad_relevant"]]
        bars = ax.barh(plot_df["pathway"], plot_df["pct_patients"],
                       color=colors, alpha=0.85, edgecolor="white")
        ax.set_xlabel("% Patients Activated (NES > 0, FDR < 0.25)", fontsize=10)
        ax.set_title(f"Top {top_n} Most Commonly Activated Pathways — LUAD Cohort (n={len(pw_df.dropna())})",
                     fontsize=10)
        ax.axvline(50, color="gray", linestyle="--", linewidth=0.8, alpha=0.6)
        for bar, val in zip(bars, plot_df["pct_patients"]):
            ax.text(val + 0.5, bar.get_y() + bar.get_height() / 2,
                    f"{val:.0f}%", va="center", fontsize=8)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        from matplotlib.patches import Patch
        ax.legend(handles=[Patch(color="#2ca02c", label="LUAD-relevant"),
                            Patch(color="#4393c3", label="Other")],
                  fontsize=8, loc="lower right")
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

        with st.expander("View full table"):
            st.dataframe(pw_df[["pathway", "n_activated", "n_suppressed",
                                 "pct_patients", "mean_nes", "luad_relevant"]],
                         use_container_width=True)
    else:
        st.info("Run `python modules/06_pathway/luad_pathway.py --summarize` to generate cross-sample summary.")


# ══════════════════════════════════════════════════════════════════════════════
# 07 · ESM2 PROTEIN FEATURES
# ══════════════════════════════════════════════════════════════════════════════

elif page == "07 · ESM2":
    st.header("07 · ESM2 Protein Features")
    st.caption("Per-site 1280-dim embeddings · masked-marginal log-odds · variant effect prediction")

    _m06_samples = discover_module_samples(OUTPUT / "07_esm2", "_esm2_summary.png")
    sample = st.selectbox("Patient", _m06_samples or SAMPLES, key="sel_m06",
                          help=f"{len(_m06_samples)} patients with ESM2 output")

    st.warning(
        "**Module 06 requires GPU acceleration and is excluded from the default pipeline run.** "
        "To generate results: `python run_all.py --include_esm2 --sample TCGA-86-A4D0`"
    )

    st.markdown("""
    **What this module does:**

    For each missense mutation identified in Module 02, ESM2-650M (Meta AI) is used to:
    1. Retrieve the canonical protein sequence from UniProt
    2. Extract the **1280-dim hidden state** at the mutation site (wild-type and mutant)
    3. Compute **masked-marginal log-odds** = log P(mut_aa | context) − log P(wt_aa | context)
    4. Compute **delta embedding** = mut_emb − wt_emb as a structural perturbation proxy

    These features can be used to predict whether a mutation is likely pathogenic.
    """)

    st.divider()

    # ESM2 summary image (if available)
    img = OUTPUT / "07_esm2" / sample / f"{sample}_esm2_summary.png"
    show_image(img, caption=f"ESM2 mutation scoring summary — {sample}")

    # Mutation scores table
    scores_path = OUTPUT / "07_esm2" / sample / "mutation_scores.tsv"
    if scores_path.exists():
        st.subheader("Mutation Scores")
        show_table(scores_path, caption=f"ESM2 log-odds and oncogenicity scores — {sample}")
    else:
        st.subheader("Mutation Scores")
        st.info("No ESM2 scores available yet. Run module 06 to generate.")

    # Feature file availability
    st.divider()
    st.subheader("Feature Files")
    feature_files = [
        ("wt_features.npy",    "Wild-type site embeddings (N × 1280)"),
        ("mut_features.npy",   "Mutant site embeddings (N × 1280)"),
        ("delta_features.npy", "Delta embeddings — mut minus wt (N × 1280)"),
        ("site_info.csv",      "Site metadata (gene, position, wt_aa, mut_aa)"),
    ]
    for fname, desc in feature_files:
        fpath = OUTPUT / "07_esm2" / sample / fname
        status = "✅ Available" if fpath.exists() else "⏳ Not yet generated"
        st.markdown(f"- `{fname}` — {desc} &nbsp;&nbsp; **{status}**")


# ══════════════════════════════════════════════════════════════════════════════
# (07 · Drug Mapping — internal layer, not shown in sidebar)
# ══════════════════════════════════════════════════════════════════════════════

elif page == "07 · Drug Mapping":
    st.header("07 · Drug Mapping")
    st.caption("NCCN/FDA guidelines · CIViC evidence · therapy recommendations")

    # Cross-sample heatmap — square image, center at 55% width
    st.subheader("Drug Actionability — All Samples")
    img_heatmap = OUTPUT / "07_drug_mapping" / "drug_actionability_heatmap.png"
    _, mid, _ = st.columns([0.225, 0.55, 0.225])
    with mid:
        show_image(img_heatmap, caption="Drug actionability heatmap — all samples × genes")

    st.divider()

    # Per-sample selector — discover all samples that have a drug report file
    drug_samples = discover_module_samples(OUTPUT / "07_drug_mapping", "_drug_report.tsv")

    st.subheader("Per-Sample Drug Report")
    if not drug_samples:
        st.info("No drug reports found. Run `python run_all.py --modules 02 07` to generate them.")
        st.stop()

    st.caption(
        f"Drug reports available for {len(drug_samples)} samples."
    )
    selected = st.selectbox(
        "Select sample",
        options=drug_samples,
        index=0,
        key="drug_sample",
    )

    img_report = OUTPUT / "07_drug_mapping" / selected / f"{selected}_drug_report.png"
    show_image(img_report, caption=f"Drug report — {selected}")

    show_table(
        OUTPUT / "07_drug_mapping" / selected / f"{selected}_drug_report.tsv",
        caption=f"Recommended therapies — {selected}",
    )

    st.divider()

    st.subheader("Cross-Sample Drug Summary")
    show_table(
        OUTPUT / "07_drug_mapping" / "all_samples_drug_summary.tsv",
        caption="Drug recommendations across all samples",
    )

    st.divider()

    # LUAD drug context
    with st.expander("LUAD Targeted Therapy Reference (NCCN/FDA)"):
        st.markdown("""
        | Gene / Alteration | Drug(s) | Evidence |
        |-------------------|---------|----------|
        | EGFR exon 19 del / L858R | Osimertinib (1st line) | FDA approved |
        | EGFR T790M (resistance) | Osimertinib | FDA approved |
        | EGFR exon 20 ins | Amivantamab + Lazertinib | FDA approved |
        | ALK fusion | Alectinib / Lorlatinib | FDA approved |
        | ROS1 fusion | Crizotinib / Entrectinib | FDA approved |
        | RET fusion | Selpercatinib | FDA approved |
        | MET exon 14 skip | Capmatinib / Tepotinib | FDA approved |
        | BRAF V600E | Dabrafenib + Trametinib | FDA approved |
        | KRAS G12C | Sotorasib / Adagrasib | FDA approved |
        | NTRK fusion | Entrectinib / Larotrectinib | FDA approved |
        | HER2 mutation | Trastuzumab deruxtecan | FDA approved |
        | TMB ≥10 mut/Mb | Pembrolizumab (IO) | FDA approved |
        | STK11 loss | IO resistance — prefer chemo | NCCN note |
        """)


# ══════════════════════════════════════════════════════════════════════════════
# 05 · PATHOLOGY
# ══════════════════════════════════════════════════════════════════════════════

elif page == "05 · Pathology":
    st.header("05 · Pathology")
    st.caption("H&E slide analysis · tissue segmentation · TIL scoring · TME phenotype")

    st.markdown("""
    **What this module does:**

    Analyzes H&E-stained whole slide image (WSI) thumbnails downloaded from GDC using
    classical computer vision (no GPU required):

    1. **Tissue segmentation** — Otsu thresholding to separate tissue from background
    2. **H&E color deconvolution** — separate hematoxylin (nuclei) and eosin (cytoplasm) channels
    3. **Nuclear density** — estimate tumor cellularity from nuclear staining intensity
    4. **TIL scoring** — quantify tumor-infiltrating lymphocyte density (small dark nuclei)
    5. **TME phenotype** — classify as **Inflamed** / **Excluded** / **Desert**
    """)

    st.divider()

    # ── Cohort-level summary ─────────────────────────────────────────────────
    summary_path = OUTPUT / "05_pathology" / "pathology_summary.tsv"
    if summary_path.exists():
        st.subheader("Cohort Pathology Summary")
        df_summary = pd.read_csv(summary_path, sep="\t")

        # TME phenotype distribution
        col1, col2, col3 = st.columns(3)
        tme_counts = df_summary["tme_phenotype"].value_counts() if "tme_phenotype" in df_summary.columns else {}
        tme_colors = {"Inflamed": "🟢", "Excluded": "🟡", "Desert": "🔴"}
        for col, phenotype in zip([col1, col2, col3], ["Inflamed", "Excluded", "Desert"]):
            count = tme_counts.get(phenotype, 0)
            pct   = count / len(df_summary) * 100 if len(df_summary) > 0 else 0
            col.metric(
                label=f"{tme_colors.get(phenotype, '⚪')} {phenotype}",
                value=f"{count}",
                delta=f"{pct:.0f}% of slides",
            )

        st.dataframe(df_summary, use_container_width=True, hide_index=True)
    else:
        st.info(
            "No cohort summary yet. Run M08 to generate:\n"
            "```bash\npython modules/05_pathology/luad_pathology.py\n```"
        )

    st.divider()

    # ── Per-sample pathology report ──────────────────────────────────────────
    st.subheader("Per-Sample Pathology Report")

    # Discover which samples have pathology results
    path_out = OUTPUT / "05_pathology"
    available = sorted([
        d.name for d in path_out.iterdir()
        if d.is_dir() and (d / f"{d.name}_pathology_report.png").exists()
    ]) if path_out.exists() else []

    if available:
        selected_path = st.selectbox(
            "Select sample",
            options=available,
            index=0,
        )

        report_png   = path_out / selected_path / f"{selected_path}_pathology_report.png"
        scores_tsv   = path_out / selected_path / f"{selected_path}_pathology_scores.tsv"

        # Report figure
        show_image(report_png, caption=f"Pathology report — {selected_path}")

        # Scores table
        if scores_tsv.exists():
            st.subheader("Quantitative Scores")
            df_scores = pd.read_csv(scores_tsv, sep="\t")
            # Drop internal columns
            display_cols = [c for c in df_scores.columns if not c.startswith("_")]
            st.dataframe(df_scores[display_cols], use_container_width=True, hide_index=True)

            # Highlight TME phenotype
            if "tme_phenotype" in df_scores.columns:
                tme = df_scores["tme_phenotype"].iloc[0]
                tme_info = {
                    "Inflamed":  ("🟢", "High immune infiltration — potential IO responder"),
                    "Excluded":  ("🟡", "Immune cells present but confined to stroma — partial IO resistance"),
                    "Desert":    ("🔴", "Low immune infiltration — IO likely ineffective"),
                }
                icon, desc = tme_info.get(tme, ("⚪", ""))
                st.info(f"**{icon} TME Phenotype: {tme}** — {desc}")
    else:
        st.info(
            "No pathology reports generated yet.\n\n"
            "**Step 1:** Download WSI thumbnails:\n"
            "```bash\npython data/scripts/download_wsi.py --thumbnail --test\n```\n\n"
            "**Step 2:** Run M08 analysis:\n"
            "```bash\npython modules/05_pathology/luad_pathology.py\n```"
        )

    st.divider()

    # TME × Molecular cross-reference
    with st.expander("TME Phenotype — Clinical Significance"):
        st.markdown("""
        | TME Phenotype | Cohort Rank | IO Response | Recommended Strategy |
        |---------------|-------------|-------------|----------------------|
        | **Inflamed** | Top 30% TIL density | Likely responder | Pembrolizumab / Atezolizumab |
        | **Excluded** | Middle 50% TIL density | Partial resistance | IO + anti-VEGF combination |
        | **Desert** | Bottom 20% TIL density | Unlikely responder | Targeted therapy / Chemotherapy |

        Classification uses cohort-wide percentile thresholds (70th / 20th percentile of TIL density),
        not fixed absolute values. Cross-reference with M04 (single-cell TME) for integrated
        treatment decision support.
        """)


# ══════════════════════════════════════════════════════════════════════════════
# 09 · MULTIMODAL INTEGRATION
# ══════════════════════════════════════════════════════════════════════════════

elif page == "09 · Multimodal Integration":
    st.header("09 · Multimodal Integration")
    st.caption("M02 variants + M08 TME phenotype → rule-based treatment recommendations")

    st.markdown("""
    **Integration logic (NCCN NSCLC 2024 + FDA approvals):**

    | Priority | Signal | Action |
    |----------|--------|--------|
    | 1 | Targetable driver mutation (EGFR/KRAS/ALK/ROS1/RET/MET/BRAF/ERBB2/NTRK) | Matched targeted therapy |
    | 2 | Inflamed TME or High TMB (≥10 mut/Mb) | Immunotherapy (Pembrolizumab) |
    | 3 | No driver + Desert TME | Platinum-based chemotherapy |
    """)

    st.divider()

    # ── Cohort summary ────────────────────────────────────────────────────────
    summary_path = OUTPUT / "09_integration" / "integration_summary.tsv"
    if summary_path.exists():
        st.subheader("Cohort Integration Summary")
        df_sum = pd.read_csv(summary_path, sep="\t")

        # Top-level metrics
        n = len(df_sum)
        n_targeted  = (df_sum["n_targeted"] > 0).sum() if "n_targeted" in df_sum.columns else 0
        n_tmb_high  = df_sum["tmb_high"].sum()           if "tmb_high"  in df_sum.columns else 0
        n_combo     = (df_sum["n_combination"] > 0).sum() if "n_combination" in df_sum.columns else 0
        mean_io     = df_sum["io_score"].mean()           if "io_score"  in df_sum.columns else 0

        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Total Patients",       n)
        col2.metric("With Targeted Drugs",  f"{n_targeted} ({n_targeted/n:.0%})")
        col3.metric("High TMB (≥10 mut/Mb)",f"{n_tmb_high} ({n_tmb_high/n:.0%})")
        col4.metric("Mean IO Score",        f"{mean_io:.1f} / 100")

        col5, col6, col7 = st.columns(3)
        col5.metric("With Combo Therapy Suggestions", f"{n_combo} ({n_combo/n:.0%})")
        if "tme_phenotype" in df_sum.columns:
            n_inflamed = (df_sum["tme_phenotype"] == "Inflamed").sum()
            n_excluded = (df_sum["tme_phenotype"] == "Excluded").sum()
            col6.metric("Inflamed TME", f"{n_inflamed} ({n_inflamed/n:.0%})")
            col7.metric("Excluded TME", f"{n_excluded} ({n_excluded/n:.0%})")

        st.divider()

        # IO score distribution
        if "io_score" in df_sum.columns:
            st.subheader("Immunotherapy Score Distribution")
            import matplotlib
            matplotlib.use("Agg")
            import matplotlib.pyplot as plt
            fig, ax = plt.subplots(figsize=(8, 3))
            ax.hist(df_sum["io_score"].dropna(), bins=20, color="#1a9850", alpha=0.8,
                    edgecolor="white")
            ax.axvline(x=50, color="#d73027", linestyle="--", linewidth=1.2,
                       label="Score = 50")
            ax.set_xlabel("IO Score (0-100)", fontsize=10)
            ax.set_ylabel("Patients", fontsize=10)
            ax.set_title("Multi-Dimensional Immunotherapy Score\n"
                         "(TMB + TME + PD-L1 + IFN-γ signature)", fontsize=10)
            ax.legend(fontsize=9)
            fig.tight_layout()
            st.pyplot(fig, use_container_width=False)
            plt.close()

        st.divider()

        # Top targeted drugs
        st.subheader("Top Targeted Drug Distribution")
        if "top_targeted_drug" in df_sum.columns:
            drug_counts = df_sum["top_targeted_drug"].value_counts()
            drug_counts = drug_counts[drug_counts.index != "None"]
            if not drug_counts.empty:
                drug_df = drug_counts.reset_index()
                drug_df.columns = ["Drug", "Patients"]
                st.dataframe(drug_df, use_container_width=False, hide_index=True)

        st.divider()

        # Full cohort table
        with st.expander("Full Cohort Summary Table"):
            st.dataframe(df_sum, use_container_width=True, hide_index=True)

    else:
        st.info(
            "Integration summary not yet generated.\n\n"
            "**Step 1:** Run M02 variant annotation:\n"
            "```bash\npython modules/02_variants/luad_pcgr.py\n```\n\n"
            "**Step 2:** Run M07, M08, M03 (optional, for richer scoring):\n"
            "```bash\npython modules/07_drug_mapping/luad_drug_mapping.py\n"
            "python modules/05_pathology/luad_pathology.py\n"
            "python modules/03_expression/luad_expression.py\n```\n\n"
            "**Step 3:** Run M09 integration:\n"
            "```bash\npython modules/09_integration/luad_integration.py\n```"
        )

    st.divider()

    # ── Per-patient recommendation ────────────────────────────────────────────
    st.subheader("Per-Patient Recommendation")

    integration_dir = OUTPUT / "09_integration"
    _m09_all = patients_for_page("09 · Multimodal Integration")
    available = sorted([
        s for s in _m09_all
        if (integration_dir / s / f"{s}_recommendation.tsv").exists()
    ]) if integration_dir.exists() else []

    if available:
        selected = st.selectbox("Select patient", options=available)

        rec_tsv    = integration_dir / selected / f"{selected}_recommendation.tsv"
        report_png = integration_dir / selected / f"{selected}_integration_report.png"

        if report_png.exists():
            st.image(str(report_png), use_container_width=True)

        if rec_tsv.exists():
            st.subheader("All Ranked Recommendations")
            df_rec = pd.read_csv(rec_tsv, sep="\t")

            ICONS = {
                "Targeted Therapy":   "🔵",
                "Immunotherapy":      "🟢",
                "Combination Therapy":"🟣",
                "Chemotherapy":       "🔴",
            }
            df_display = df_rec.copy()
            df_display["category"] = df_display["category"].apply(
                lambda c: f"{ICONS.get(c, '⚪')} {c}"
            )

            # Score bar as emoji-style text
            def score_bar(s):
                filled = int(round(s / 10))
                return "█" * filled + "░" * (10 - filled) + f"  {s}"
            if "confidence" in df_display.columns:
                df_display["confidence"] = df_display["confidence"].apply(score_bar)

            display_cols = [
                "rank", "category", "drug", "drug_class",
                "oncokb_level", "amp_tier", "escat_tier",
                "evidence", "line", "confidence",
                "data_layers", "rationale", "combination_basis",
            ]
            st.dataframe(
                df_display[[c for c in display_cols if c in df_display.columns]],
                use_container_width=True,
                hide_index=True,
            )

            # Evidence legend
            with st.expander("Evidence Grading Reference"):
                st.markdown("""
| OncoKB Level | AMP/ASCO/CAP Tier | Meaning |
|---|---|---|
| Level 1 | Tier I-A | FDA-approved biomarker + same tumor type |
| Level 2 | Tier I-B | NCCN guideline recommendation |
| Level 3A | Tier II-C | Clinical trial evidence / Investigational |
| Level 3B | Tier II-D | Cross-tumor type extrapolation |
| Level 4 | Tier II-D | Preclinical / biological evidence only |
| ESCAT Tier V | — | Combination therapy (co-targeting rationale) |

**IO Score** (0–100) = TMB (0–40) + TME (0–40) + PD-L1 expression (0–15) + IFN-γ signature (0–15) − IO resistance penalty (−20 if STK11/KEAP1/NFE2L2 co-mutation)
                """)
    else:
        st.caption("No per-patient integration reports found. Run M09 to generate them.")


# ══════════════════════════════════════════════════════════════════════════════
# 08 · IO ML
# ══════════════════════════════════════════════════════════════════════════════

elif page == "08 · IO ML":
    st.header("08 · IO ML — Immunotherapy Response Prediction")
    st.caption("TIS · CYT · TIDE · IMPRES · Composite IO Score · IO Resistance")

    cohort_path = OUTPUT / "08_io_ml" / "io_cohort_scores.tsv"

    if cohort_path.exists():
        df_io = pd.read_csv(cohort_path, sep="\t")
        n = len(df_io)
        cls_counts = df_io["io_class"].value_counts() if "io_class" in df_io.columns else {}

        c1, c2, c3 = st.columns(3)
        c1.metric("🟢 Likely Responder",     str(cls_counts.get("Likely_Responder", 0)),
                  f"{100*cls_counts.get('Likely_Responder',0)/n:.0f}%")
        c2.metric("🟡 Uncertain",            str(cls_counts.get("Uncertain", 0)),
                  f"{100*cls_counts.get('Uncertain',0)/n:.0f}%")
        c3.metric("🔴 Likely Non-Responder", str(cls_counts.get("Likely_Non_Responder", 0)),
                  f"{100*cls_counts.get('Likely_Non_Responder',0)/n:.0f}%")

        st.divider()
        show_image(OUTPUT / "08_io_ml" / "io_cohort_heatmap.png",
                   caption="Cohort IO ML — score distribution · component heatmap · class distribution")

        st.divider()
        st.subheader("Per-Patient IO Profile")
        _m08io_samples = patients_for_page("08 · IO ML")
        if _m08io_samples:
            sel = st.selectbox("Select patient", _m08io_samples, key="m08io_sample")
            pat_path = OUTPUT / "08_io_ml" / sel / f"{sel}_io_scores.tsv"
            if pat_path.exists():
                df_pat = pd.read_csv(pat_path, sep="\t")
                io_class = df_pat["io_class"].iloc[0] if "io_class" in df_pat.columns else "Unknown"
                io_score = df_pat["io_score"].iloc[0] if "io_score" in df_pat.columns else 0
                cls_info = {
                    "Likely_Responder":     ("🟢", "High IO response potential"),
                    "Uncertain":            ("🟡", "Uncertain — consider multi-modal evidence"),
                    "Likely_Non_Responder": ("🔴", "Low IO response potential"),
                }
                icon, desc = cls_info.get(io_class, ("⚪", ""))
                st.info(f"**{icon} {io_class.replace('_',' ')}** (Score: {io_score}) — {desc}")

                score_cols = ["tis", "cyt", "tide_net", "impres"]
                available  = [c for c in score_cols if c in df_pat.columns and pd.notna(df_pat[c].iloc[0])]
                if available:
                    import matplotlib.pyplot as plt
                    labels = {"tis": "TIS", "cyt": "CYT", "tide_net": "TIDE (net)", "impres": "IMPRES"}
                    vals   = [float(df_pat[c].iloc[0]) for c in available]
                    fig, ax = plt.subplots(figsize=(8, 3))
                    ax.bar([labels.get(c, c) for c in available], vals, color="#4e79a7", edgecolor="white")
                    ax.set_title(f"IO Algorithm Scores — {sel}", fontsize=11)
                    ax.set_ylabel("Score")
                    fig.tight_layout()
                    st.pyplot(fig)
                    plt.close(fig)

                if df_pat.get("io_resistant", pd.Series([False])).iloc[0]:
                    res_genes = df_pat["resistance_genes"].iloc[0] if "resistance_genes" in df_pat.columns else ""
                    st.warning(f"⚠️ IO Resistance flag: {res_genes} mutation detected")
            else:
                st.info("Per-patient IO scores not yet generated. Run: `python modules/08_io_ml/luad_io_ml.py`")

        st.divider()
        with st.expander("Algorithm Reference"):
            st.markdown("""
| Algorithm | Genes/Logic | Reference |
|-----------|-------------|-----------|
| **TIS** | 18-gene Tumor Inflammation Signature — mean log₂(TPM+1) | Ayers et al., JCI 2017 |
| **CYT** | Cytolytic activity — mean(log₂GZMA, log₂PRF1) | Rooney et al., Cell 2015 |
| **TIDE** | Net T-cell Dysfunction − Exclusion score | Jiang et al., Nat Med 2018 |
| **IMPRES** | 15 checkpoint gene-pair comparisons, score 0–15 | Auslander et al., Nat Med 2019 |
| **Resistance** | STK11 / KEAP1 / NFE2L2 somatic mutation | Skoulidis et al., Cancer Cell 2018 |
| **Composite** | TIS×40% + IMPRES×25% + TIDE×25% + CYT×10% → 0–100 | This study |
            """)
    else:
        st.info("IO ML scores not yet generated. Run: `python modules/08_io_ml/luad_io_ml.py`")


# ══════════════════════════════════════════════════════════════════════════════
# 10 · CLINICAL RECOMMENDATION
# ══════════════════════════════════════════════════════════════════════════════

elif page == "10 · Clinical Recommendation":
    st.header("10 · Clinical Recommendation")
    st.caption("Multi-omics–guided treatment recommendations · OncoKB · AMP/ASCO/CAP · ESCAT")

    _m10_samples = patients_for_page("10 · Clinical Recommendation")
    sel_sample = st.selectbox(
        "Select patient", _m10_samples or [],
        key="m10_sample",
        index=_m10_samples.index("TCGA-86-A4D0") if _m10_samples and "TCGA-86-A4D0" in _m10_samples else 0,
    )

    if sel_sample:
        rec_tsv = OUTPUT / "09_integration" / sel_sample / f"{sel_sample}_recommendation.tsv"
        rep_img = OUTPUT / "09_integration" / sel_sample / f"{sel_sample}_integration_report.png"

        show_image(rep_img, caption=f"Integration report — {sel_sample}")

        if rec_tsv.exists():
            st.subheader("Treatment Recommendations")
            df_rec = pd.read_csv(rec_tsv, sep="\t")
            ICONS = {
                "Targeted Therapy":    "🔵",
                "Immunotherapy":       "🟢",
                "Combination Therapy": "🟣",
                "Chemotherapy":        "🔴",
            }
            df_rec["category"] = df_rec["category"].apply(lambda c: f"{ICONS.get(c,'⚪')} {c}")
            display_cols = [
                "rank", "category", "drug", "drug_class",
                "oncokb_level", "amp_tier", "evidence", "line",
                "confidence", "data_layers", "rationale",
            ]
            st.dataframe(
                df_rec[[c for c in display_cols if c in df_rec.columns]],
                use_container_width=True, hide_index=True,
            )
        else:
            st.info("Recommendations not yet generated. Run M09 integration pipeline first.")
